### ISSUE TITLE
Jill of the Jungle 2 & 3 crash on start-up

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#101]
I tried them with both latest DOSEMU2 devel and the 1.5.0 tarball (does not seem to be a regression).
With DOSEMU2:
======================= ENTER CPU-EMU ===============

!!! Unimplemented 0f f4 06 at 00000003
ERROR: EMU86: error 2
coopthreads stopped
======================= LEAVE CPU-EMU ===============

I'm using Ubuntu 14.04 AMD64.

More info about the games:
http://www.abandonia.com/en/games/26436/Jill+of+the+Jungle+-+Jill+Goes+Underground.html
http://www.abandonia.com/en/games/26439/Jill+of+the+Jungle+-+Jill+Saves+the+Prince.html

**Comment by jschwartzenberg** [comment]
With the now deleted kvm2 branch and kvm enabled, I could play both Jill 2 and 3.
With the current kvm branch and kvm disabled, they crash.

Introducing kvm and disabling/removing the emulation may solve this.

**Comment by jschwartzenberg** [comment]
I can't reproduce this anymore. I tried multiple emulation settings on both a 32-bit and a 64-bit system, no crash anymore with current GIT.
Performance on 32-bit seems to be better in some situations than on 64-bit with KVM.

**Comment by stsp** [comment]
Who fixed that?
Please find out, if possible.
Lets close this.

**Comment by jschwartzenberg** [comment]
I did a bisect and it came up with this commit actually!
2ea10723e4f15ead992d98b568c46b63c7ce653b is the first bad commit
commit 2ea10723e4f15ead992d98b568c46b63c7ce653b
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Thu Nov 12 17:03:00 2015 +0300

    pic: add horrible hack to fix bug #99
    
    I don't know how much will this break.
    The alternative would be to revert 5ee681a

**Comment by stsp** [comment]
OK but does the commit 5ee681aa114 introduce
a regression or what?

**Comment by jschwartzenberg** [comment]
Yep, spot on! That commit originally broke it.

**Comment by stsp** [comment]
OK, good that it is now fixed.
But the fix 2ea1072 will not fix all breakages of
5ee681a. Though for now we don't yet have the
unfixed examples, which is quite good (and do not
have the examples broken with 2ea1072 itself).
Hope it will remain so...

**Comment by jschwartzenberg** [comment]
Yes, as far these games, as far as I can see they are completely with current DOSEMU. I managed to complete 3 and got very far in 2.

**Comment by jschwartzenberg** [comment]
It seems this problem is back. Sometimes the games do run, but especially the second game tends to crash on start-up.
Note that a download can also be found here: https://www.xtcabandonware.com/game/1453/jill-of-the-jungle-jill-goes-underground
And the third one: https://www.xtcabandonware.com/game/1452/jill-of-the-jungle-jill-saves-the-prince

(It seems a lot of info on that site is mixed up/incorrect. Probably too much XTC...)

**Comment by jschwartzenberg** [comment]
Also there are audio issues with both 2 & 3 when they do run.

**Comment by stsp** [comment]
Please enable $_timer_tweaks

**Comment by jschwartzenberg** [comment]
That seems to avoid the crash indeed. Still quite a bit of timing issues and bad audio. I don't think I had that back in 2016. Should I create a new ticket for this?

**Comment by stsp** [comment]
Only if the problems are
very prominent and easy
to reproduce.

**Comment by jschwartzenberg** [comment]
Yeah, they are rather prominent. Certainly if you compare the result to DOSBox.

**Comment by stsp** [comment]
Not dosbox, the difference with
2016 must be prominent. Then
its a regression.

**Comment by jschwartzenberg** [comment]
Yeah, I am pretty sure that I would not have attempted to complete the entire game as I did back then if it ran like this ...

**Comment by jschwartzenberg** [comment]
And just now I had a crash, I cannot complete the game anymore...
