### ISSUE TITLE
Signal 11 in dosemu.bin thread in terminal mode under Ubuntu 16.04

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#165]
Since upgrading my 32 bit machine to Ubuntu 16.04, I find that dosemu2 exits with signal 11 error when run in terminal mode. I've tried booting with X/sdl and it works fine.

- default X / SDL boot starts just fine (window appears, MS-DOS 6.22 boot to command prompt)
~~~
ajb@polly:/dosemu2.git$ bin/dosemu.bin -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
~~~

- terminal mode (-td) or (-I video{none}) exits with error
~~~
ajb@polly:/dosemu2.git$ bin/dosemu.bin -n -f test-imagedir/dosemu.conf --Fimagedir test-imagedir -td
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory


DOSEMU2 2.0pre5-20160423-gb47dc37, configured: 2016-04-25 09:26:48 +0100
Please test against a recent version before reporting bugs and problems.
Submit Bugs & Patches to linux-msdos@vger.kernel.org or via http://dosemu.org.
Starting MS-DOS...

ERROR: thread got signal 11
~~~
[xenial-terminal-boot.txt](https://github.com/stsp/dosemu2/files/234259/xenial-terminal-boot.txt)

I also tried running under gdb, but didn't discover any extra info
~~~
(gdb) run -n -f test-imagedir/dosemu.conf -D+d+j+Drw --Fimagedir test-imagedir/ -o bad.txt -td
Starting program: /dosemu2.git/2.0-pre5/bin/dosemu.bin -n -f test-imagedir/dosemu.conf -D+d+j+Drw --Fimagedir test-imagedir/ -o bad.txt -td
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb7697b40 (LWP 20750)]
[New Thread 0xac42fb40 (LWP 20751)]
[New Thread 0xa3afdb40 (LWP 20752)]
ALSA lib rawmidi_hw.c:233:(snd_rawmidi_hw_open) open /dev/snd/midiC0D0 failed: No such file or directory
[New Thread 0xa2c6ab40 (LWP 20754)]


DOSEMU2 2.0pre5-20160423-gb47dc37, configured: 2016-04-25 09:26:48 +0100
Please test against a recent version before reporting bugs and problems.
Submit Bugs & Patches to linux-msdos@vger.kernel.org or via http://dosemu.org.

Thread 1 "dosemu.bin" received signal SIGSEGV, Segmentation fault.
0xa32ed6c0 in ?? ()
(gdb) bt
#0  0xa32ed6c0 in ?? ()
~~~

The runtime environment is minimal
- autoexec.bat
~~~
prompt $P$G                                                                     
path c:\bin;c:\gnu;c:\dosemu                                                    
unix -s DOSEMU_VERSION                                                          
unix -e                                                                         
~~~
- config.sys
~~~
lastdrive=Z                                                                     
files=40                                                                        
stacks=0                                                                        
buffers=10                                                                      
~~~

- dosemu.conf
~~~
$_lpt1 = ""
~~~

- git checkout was 47aabfba19bf811f4f86590ca3e9c73d4e2dfaa9

- build environment [config.txt](https://github.com/stsp/dosemu2/files/234272/config.txt)
~~~
ajb@polly:/dosemu2.git$ uname -a
Linux polly 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:34:49 UTC 2016 i686 athlon i686 GNU/Linux

ajb@polly:/dosemu2.git$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/5/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.3.1-14ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 5.3.1 20160413 (Ubuntu 5.3.1-14ubuntu2) 
~~~

**Comment by andrewbird** [comment]
Note: the git sha1 in the logs is different only because I've merged in my python test suite local branch, so consider the C source identical to the checkout I specified in the report

**Comment by andrewbird** [comment]
I'm not sure if it's significant, but on my previous test machine (Ubuntu 14.04 + HWE 4.2 kernel) VM86 was available and in use, whereas on Ubuntu 16.04 dosemu2 is currently falling back to cpu emulation.

**Comment by stsp** [comment]
I can't reproduce this.
Please see if it is not a regression of location_to_memoffs()
things 7e8fd268e
Also please install glibc-debuginfo, so that in the log we
can see an addresses passed to crashing memcmp().

**Comment by andrewbird** [comment]
Hi,
  I checked out 7e8fd26~1, rebuilt and the problem is still there.

  As this Debian based system has different package names, I believe 'libc6-dbg' is the correct package. I think the glibc debug info is already installed, so I don't understand why the info is missing.

  Incidentally why is libSDL2-2.0.so.0 in one of the backtraces, as I'm running in terminal mode only?

**Comment by stsp** [comment]
> think the glibc debug info is already installed, so I don't understand why the info is missing.

So can you figure out with gdb what do we
pass to this memcmp()?

> Incidentally why is libSDL2-2.0.so.0 in one of the backtraces, as I'm running in terminal mode only?

For sound?

**Comment by andrewbird** [comment]
Okay, I bisected this

ajb@polly:/dosemu2.git-test$ git bisect bad
c43732e9932d5275fbfb5f605def437d61ba9421 is the first bad commit
commit c43732e9932d5275fbfb5f605def437d61ba9421
Author: Stas Sergeev <stsp@users.sourceforge.net>
Date:   Sun Feb 14 00:18:34 2016 +0300

    render: initialize render thread even if no remapper created
    
    This is needed to properly update text screen and cursor for
    term plugin. [#144]

:040000 040000 92ee58df67bfab1d525de175f404d623bbe9e679 9746a4d3e7c2a06e36215d95f05ec158c8a158fd M	src
~~~
ajb@polly:/dosemu2.git-test$ git bisect log
# bad: [47aabfba19bf811f4f86590ca3e9c73d4e2dfaa9] make-tag.sh: separately tag development branch
# good: [cd796ad23f9d038cb75670cc3f15f51c800bed1c] Merge branch 'devel'
git bisect start 'HEAD' 'dosemu2-2.0pre3'
# good: [d73832e250dfb6021db9b939b0dc688fde6bb138] dpmi: allocate mem pool at dosemu startup
git bisect good d73832e250dfb6021db9b939b0dc688fde6bb138
# good: [5e596e000424334c84a41bd4539fadda9284e7ab] DPMI: allocate ldt_alias buffer from DPMI memory pool.
git bisect good 5e596e000424334c84a41bd4539fadda9284e7ab
# good: [79233b6c136d70e2097f4d41ed0d24e69e11f0f8] term: work around the Shift-F3 vs CPR confusion
git bisect good 79233b6c136d70e2097f4d41ed0d24e69e11f0f8
# bad: [289e55b16a1a3e27691582331fffcc6daa5d2f49] Make: remove docsinstall target
git bisect bad 289e55b16a1a3e27691582331fffcc6daa5d2f49
# bad: [8a4634436cae111936f20ff216104b2824a949ac] remap: fix valgrind error
git bisect bad 8a4634436cae111936f20ff216104b2824a949ac
# bad: [f4e122345e8dfb9bbaadcfb6f0d83fcaeae45584] alsa_in: dont err on EINTR from poll()
git bisect bad f4e122345e8dfb9bbaadcfb6f0d83fcaeae45584
# bad: [0ddf0195b3a1e484f0161dbeb059a3664d246261] sound: remove .owns member from recorders
git bisect bad 0ddf0195b3a1e484f0161dbeb059a3664d246261
# good: [91cd64e86391a0153de68a32535e9d831918c2a2] term: gain focus on init [#144]
git bisect good 91cd64e86391a0153de68a32535e9d831918c2a2
# bad: [6dbd0d44170e73e248f8e9743d08f0bb8414b9ce] sb: add switch to enable mpu401 intelligent mode
git bisect bad 6dbd0d44170e73e248f8e9743d08f0bb8414b9ce
# bad: [c43732e9932d5275fbfb5f605def437d61ba9421] render: initialize render thread even if no remapper created
git bisect bad c43732e9932d5275fbfb5f605def437d61ba9421
# first bad commit: [c43732e9932d5275fbfb5f605def437d61ba9421] render: initialize render thread even if no remapper created
~~~

**Comment by stsp** [comment]
Unfortunately, without an ability to reproduce,
I don't know what's wrong with this patch.
Maybe some race condition.
Would be nice if you track the bad arguments
we pass to memcmp()

**Comment by andrewbird** [comment]
Well, I made a little stub function, albeit somewhat hackish to avoid the arguments being optimised away. It seems like memcmp is being given a null pointer as the second argument

```C
__attribute__((noinline))                                                       
static int mymemcmp(const void *s1, const void *s2, size_t n)                   
{                                                                               
        if (s2 == (char *) 0xdeadbeef) {                                        
                printf("hello\n");                                              
        }                                                                       
                                                                                
        asm("");                                                                
        return memcmp(s1, s2, n);                                               
}                                                                               
```

~~~
#4  0x0808708a in dosemu_error (fmt=0x814f458 "thread got signal %i\n")         
    at utilities.c:719                                                          
        args = 0xb7696e44 "\v"                                                  
#5  0x0807ddd1 in dosemu_fault0 (signal=signal@entry=11,                        
    scp=scp@entry=0xb7696fe0) at sigsegv.c:225                                  
        tid = <optimised out>                                                   
#6  0x0807e3af in dosemu_fault (signal=11, si=0xb7696f4c, uc=0xb7696fcc)        
    at sigsegv.c:276                                                            
        scp = 0xb7696fe0                                                        
#7  <signal handler called>                                                     
No symbol table info available.                                                 
#8  __memcmp_ia32 () at ../sysdeps/i386/i686/multiarch/../memcmp.S:290          
No locals.                                                                      
#9  0x0806183c in mymemcmp (s1=s1@entry=0x82235a0 <prev_screen>, s2=0x0,        
    n=n@entry=65280) at text.c:425                                              
No locals.                                                                      
#10 0x08062002 in text_is_dirty () at text.c:438                                
        sp = <optimised out>                                                    
        ret = <optimised out>                                                   
        compare = <optimised out>                                               
#11 0x08063fc5 in render_thread (arg=0x0) at render.c:467                       
No locals.                                                                      
#12 0xb7f9a2b5 in start_thread (arg=0xb7697b40) at pthread_create.c:333         
        __res = <optimised out>                                                 
        pd = 0xb7697b40                                                         
        now = <optimised out>                                                   
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {-1208295424, 0, 4001536,    
                -1217825752, 1626944151, 1096492182}, mask_was_saved = 0}},     
          priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0,               
              cleanup = 0x0, canceltype = 0}}}                                  
        not_first_call = 0                                                      
        pagesize_m1 = <optimised out>                                           
        sp = <optimised out>                                                    
        freesize = <optimised out>                                              
        __PRETTY_FUNCTION__ = "start_thread"                                    
#13 0xb7e6216e in clone () at ../sysdeps/unix/sysv/linux/i386/clone.S:114       
No locals.                                                                      
         
~~~

**Comment by stsp** [comment]
Could you please put
if (s2 == NULL) error("mem_base=%x\n", vga.mem.base);

**Comment by andrewbird** [comment]
Here you go

~~~
DOSEMU2 2.0pre5-20160418-g47aabfb, configured: 2016-04-25 17:03:03 +0100
Please test against a recent version before reporting bugs and problems.
Submit Bugs & Patches to linux-msdos@vger.kernel.org or via http://dosemu.org.
ERROR: mem_base=0
ERROR: thread got signal 11
Starting MS-DOS...
~~~

**Comment by stsp** [comment]
Great, could you please also print
"video_initialized" variable there?

**Comment by andrewbird** [comment]
And again
~~~
DOSEMU2 2.0pre5-20160418-g47aabfb, configured: 2016-04-25 17:03:03 +0100
Please test against a recent version before reporting bugs and problems.
Submit Bugs & Patches to linux-msdos@vger.kernel.org or via http://dosemu.org.
ERROR: video_initialized=1
ERROR: mem_base=0
ERROR: thread got signal 11
Starting MS-DOS...
~~~

**Comment by stsp** [comment]
I've fixed a few small bugs that could lead
to vga.mem.base being NULL, but I am not
sure that will help. But please pull.
Also the -D9+v log would be nice.

**Comment by andrewbird** [comment]
The problem is still there. Here's the log file [bad.txt](https://github.com/stsp/dosemu2/files/235189/bad.txt) after applying your changes and removing my hack

**Comment by stsp** [comment]
In video_init() could you try to disable the entire if block:

  /* figure out which video front end we are to use */
  if (no_real_terminal()...

**Comment by stsp** [comment]
Ah, OK, I can reproduce with -td.
Why do you use -td and not -t?

**Comment by andrewbird** [comment]
Just because I want to capture the output from DOS simply

-------- Original message --------
From Stas Sergeev <notifications@github.com> 
Date: 25/04/2016  20:20  (GMT+00:00) 
To stsp/dosemu2 <dosemu2@noreply.github.com> 
Cc Andrew Bird <ajb@spheresystems.co.uk>,Author <author@noreply.github.com> 
Subject Re: [stsp/dosemu2] Signal 11 in dosemu.bin thread in terminal mode
  under Ubuntu 16.04 (#165) 
 
Ah, OK, I can reproduce with -td.
Why do you use -td and not -t?

**Comment by andrewbird** [comment]
Looks good to me, thanks!
