### ISSUE TITLE
SciTech Display Doctor 5.3a crashes DOSEMU

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#264]
Downloads for SDD can be found here:
ftp://cyberia.dnsalias.com/pub/filebase/freedos/

Registration codes for SDD can be found here:
ftp://cyberia.dnsalias.com/pub/filebase/freedos/00_INDEX.TXT

It appears the same problem occurs with both version 5.3a and 6.53, but I could only install 5.3a inside Windows 3.1. (In Windows for Workgroups 3.11 I could install 6.53.)

Even though the autodetection of SDD fails, it's possible to set a graphics chip configuration manually. A screenshot which shows this:
![dosemu-sdd53a-config-adapter](https://cloud.githubusercontent.com/assets/877112/20455442/7199e54e-ae5c-11e6-89ec-0b81c02ec10d.png)

I tried a few variantions of the Trident TVGA8900C, but no matter what I select, DOSEMU crashes with this error when clicking ok:
```
ERROR: GS selector invalid: 0x10A7, type=0 np=1
```
[boot.log.txt](https://github.com/stsp/dosemu2/files/601438/boot.log.txt)

**Comment by stsp** [comment]
This needs -D9+M

**Comment by jschwartzenberg** [comment]
Here it is!
[boot.log.gz](https://github.com/stsp/dosemu2/files/604725/boot.log.gz)

**Comment by stsp** [comment]
Should now be fixed, or please update the log.

**Comment by jschwartzenberg** [comment]
I can confirm the crash is gone with both versions! SDD still doesn't work though. I guess it relies on some specific hardware features that are not emulated.
