### ISSUE TITLE
win31 SB16 driver gives a crash

### ISSUE THREAD

**Issue by jschwartzenberg** [stsp/dosemu2#363]
Installing the SB16 driver causes Windows 3.1 startup to crash dosemu. The errors are a bit different depending on whether win/s or win/3 is ran.

**Comment by stsp** [comment]
Please add urls.

**Comment by jschwartzenberg** [comment]
Here's the image I use for testing: https://yadi.sk/d/xCZvUk8A3H3VfZ 

A lot of other drivers can be found here as well: http://www.vogonsdrivers.com/index.php?catid=7&menustate=42,35
I forgot which one I used exactly for that installation.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by jschwartzenberg** [comment]
It still crashes for me here with a message like:
```
ERROR: general protection at 0x41d65000: 2e
```
This seems to occur when Windows is about to play the start-up sound.

**Comment by stsp** [comment]
But for me it works perfectly with PC-DOS.
Can you check that?

**Comment by jschwartzenberg** [comment]
I don't have an installed copy. Is there an image you could easily share? Did you also test with the image I provided here?

**Comment by stsp** [comment]
OK, I just checked with clean fd installation
and with your image of course.

**Comment by stsp** [comment]
Except that I am using it not as C but
as G. fd occupies first drives as by default.
Could you test that?

**Comment by jschwartzenberg** [comment]
Yep, then it works and with sound too! So this crash only happens when using just my image as c:.

**Comment by stsp** [comment]
So is this NOTABUG?
I guess I spent too many efforts to
fix what appeared to be a configuration
problem. :)
Btw, how do you suppose to use it as
C? For me windows simply complains
that himem.sys is not loaded, and does
not even start. This image is not supposed
to be booted under dosemu.

**Comment by jschwartzenberg** [comment]
It works fine here as C. Put the image in it's own directory then:
set dosemu__hdimage to point to 'that directory + /*'
Then run dosemu.
Then 'windows\win' starts Windows.

**Comment by stsp** [comment]
OK, I was using `$_emusys` so the boot
was wrong.
This is still NOTABUG, just remove csp.sys
from config.sys and everything is fine.

**Comment by jschwartzenberg** [comment]
Alright. But does it make sense that dosemu crashes when csp.sys is loaded?

**Comment by stsp** [comment]
Who knows?
Maybe the sb16snd.drv detects csp.sys
and talks to it instead of doing things on
its own? No idea.
It all ends when the driver calls realmode
to address 0:0, so obviously if it wants to
talk to csp.sys, it doesn't succeed.

**Comment by stsp** [comment]
> Alright. But does it make sense that dosemu crashes when csp.sys is loaded?

Yes.
All you had to do to get it working, is:
`set SOUND=C:\SB16`

Spectacular example of NOTABUG. :)

**Comment by jschwartzenberg** [comment]
Maybe it would be possible to have more clear errors when there are such crashes? Currently it's not clear for me whether a program does something illegal or whether it may be a dosemu problem.

**Comment by stsp** [comment]
Maybe you can fill a bug report to Creative
and ask them to make their driver not to crash
but to display an error. Though I really suspect
that displaying an error from the driver under
windows may be difficult.

In a mean time would you like to update the
documentation about installing this driver?

**Comment by jschwartzenberg** [comment]
As a user I don't see the difference between a crash inside of dosemu and of dosemu itself if this is a crash in the Creative driver. I understand there's no easy way to indicate this difference?

Of course I'll update the docs. I hope I can find an easy way to install this driver without needing an image file.

**Comment by stsp** [comment]
> As a user I don't see the difference between a crash inside of dosemu and of dosemu itself

You should.
```
ERROR: general protection at 0x41d65000: 2e
```
is a crash inside dosemu (which, of course, can be
caused by a dosemu bug too, but in this case - by
your misconfiguration).
In case of the dosemu crash you would see the
message asking to open a bug report, plus a log
full of info. So this is really visible.

> I hope I can find an easy way to install this driver without needing an image file.

We can also host it ourselves, as we do for mouse.
I can even write oemsetup.inf these days. :)
Of course it would be good if you find it elsewhere.

**Comment by stsp** [comment]
By the way, I think this driver will lock up on qemu.
Would be interesting is you can check that.

**Comment by jschwartzenberg** [comment]
If there would be any way to have more clear crash messages (especially for the case which doesn't appear to be a dosemu bug), I would really encourage that.

Yeah it would be nice to not have to host it, but let's see :)

Yeah, I think it should be np to boot the image in qemu.

**Comment by jschwartzenberg** [comment]
You're right about qemu. With csp.sys, it prints these warnings:
```
sb16: warning: command 0x5,2 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0x4,1 is not truly understood yet
sb16: warning: command 0x8,0 is not truly understood yet
sb16: warning: command 0x3,0 is not truly understood yet
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
```

And the Windows driver (with csp.sys disabled) prevents Windows from starting and these warnings are printed:
```
sb16: warning: command 0xf,1 is not truly understood yet
sb16: warning: command 0xe,2 is not truly understood yet
```

**Comment by stsp** [comment]
That have bug with PIC, which is they think
in edge-trigger mode the IRR bits cannot be
untriggered. This is wrong (according to datasheet),
and the sb16 driver expects the untriggering to work
correctly. You can try something like this:
```
diff --git a/hw/intc/i8259.c b/hw/intc/i8259.c
index c2607a5..be68ddb 100644
--- a/hw/intc/i8259.c
+++ b/hw/intc/i8259.c
@@ -173,6 +173,7 @@ static void pic_set_irq(void *opaque, int irq, int level)
             }
             s->last_irr |= mask;
         } else {
+            s->irr &= ~mask;
             s->last_irr &= ~mask;
         }
     }
```
but make sure to disable KVM as KVM has its own PIC.

**Comment by jschwartzenberg** [comment]
I don't have the qemu sources handy, but maybe I'll try that. Why don't you try it? :)

Btw. I found a driver set that fully installs from within Windows 3.1, but its InstallShield installer hangs at the start of the installation, with 100% CPU usage, it can be found here:
http://www.vogonsdrivers.com/getfile.php?fileid=1002&menustate=42,35

**Comment by stsp** [comment]
You don't need installshield.
You need to copy win31/disk4 and in
control panel enter Drivers, then add
the driver and point to this disk4.
Unfortunately this ends with "file not
found" for some reason, but maybe
it will work on hdimage?

**Comment by stsp** [comment]
installshield monitors bytes 40:40 and 40:42
to wait until disk IO is completed. Since we are
redirected, this have nothing to do with disk IO,
so it waits forever.
Will not ever work on dosemu.

**Comment by jschwartzenberg** [comment]
I didn't have much time to look at the individual disks directories anymore, but I can imagine it would indeed be possible to obtain the right files from them directly. Maybe some of the files it can't find are in the other disk directories.

I can imagine quite a few applications have an InstallShield installer, so it would be really nice if we could still find some solution for that.

**Comment by stsp** [comment]
This can wait.
Please find the time to install
directly from disk4. :) No, it doesn't
need files from another disk, you
can see that in oemsetup.inf.

**Comment by stsp** [comment]
Does installshield work fine on dosbox, pcem, qemu?

**Comment by jschwartzenberg** [comment]
I just tried it inside PCEM it does get a bit further, but then it says it can't detect a SB16. Here are the executables that are extracted to perform the installation. I think the first one is the culprit that breaks on dosemu. It can be ran directly from the disk1 directory.
[_INS0433._MP.gz](https://github.com/stsp/dosemu2/files/956223/_INS0433._MP.gz)
[_INZ0433._MP.gz](https://github.com/stsp/dosemu2/files/956224/_INZ0433._MP.gz)

Trying to use the files from disk4 directly inside pcem has the same effect as in dosemu. I think this oemsetup.inf is broken.

**Comment by stsp** [comment]
Does _this_ installshield work under wine?

**Comment by jschwartzenberg** [comment]
Yes, it works in Wine. It fails at detecting the SB16 (like in PCEM). So it seems WIne handles this InstallShield somehow.

I found another working driver which has a proper oemsetup.inf here btw:
http://www.fdd5-25.net/sounddrv.htm
Midi is not entirely working with this one though, I've had dosemu hang with high CPU usage when playing a midi file multiple times already.

**Comment by stsp** [comment]
Then perhaps it is not installshield
itself but some windows internals do
tricks with hdd/floppies. Or maybe wine
emulates too much? :) Worth taking a
look perhaps.

Who cares about midi, btw, was it adlib
or mpu401? If the driver works - great!

**Comment by jschwartzenberg** [comment]
It's adlib. There are a lot of Windows games that use it to play music.

**Comment by stsp** [comment]
OK, since installshield works everywhere else,
you can open a separate bug for it, and I'll see if
some dummy trick is possible to get it through
the hang.

**Comment by stsp** [comment]
InstallShield support is now added.

**Comment by jschwartzenberg** [comment]
Yep, the installer now passes that part. It doesn't detect the card it's looking for after that though, just like PCEM:
![dosemu-win31-vibra16](https://cloud.githubusercontent.com/assets/877112/25781740/aa95741a-333d-11e7-9d90-8c37d8e9540f.png)

**Comment by stsp** [comment]
We don't support vibra.
In fact, we only support pre-PNP SB16 variants.
You may want to open the ticket about this,
but adding the pnp variants is a big task, so
no promises.

**Comment by jschwartzenberg** [comment]
I was reading a bit about the differences between the Vibra and SB16. The Vibra seems to lack treble and bass control. There are also non-PnP editions of this card. It's not really clear why some drivers are specifically marked for Vibra as in general it uses the same SB16 drivers.

Maybe there is some detection trick that this installer uses to differentiate the Vibra from a classic SB16, but if it would not be trivial to support that, I don't think it's worth the effort as the effective differences should be minimal.

**Comment by stsp** [comment]
If there are the non-PnP editions of vibra
(any proof), then I would highly suspect the
detection will still fail.
You can try this under dosbox first, and
then under dosbox-x. doxbox-x seems to
support the pnp variants, so if it shows
the difference, then this is it.

**Comment by stsp** [comment]
> If there are the non-PnP editions of vibra
> (any proof?), then I would highly suspect
> the detection to still fail.

The confusing statement above implies that
the driver expects the PnP version. So you
either need a non-pnp driver or the detection
will still fail even on vibra itself.

**Comment by jschwartzenberg** [comment]
If I understand you correctly, you've already observed that this installer explicitly checks for PnP stuff? Or you want to do the test with dosbox and dosbox-x to verify that?

**Comment by jschwartzenberg** [comment]
Here are lists of the different Creative cards, they have a different ordering:
http://ask.europe.creative.com/wwfrench/general/products_list_audio.htm
http://ask.europe.creative.com/wwenglish/general/products_list_audio.htm
http://support.creative.com/kb/ShowArticle.aspx?sid=10846
There are both VIBRA models with and without PnP listed there.

It appears in general that the non-PnP VIBRAs are rare though. Here's a forum post which also mentions non-PnP VIBRAs exist:
http://www.vcfed.org/forum/archive/index.php/t-27371.html

**Comment by stsp** [comment]
> If I understand you correctly, you've already observed that this installer explicitly checks for PnP stuff?

Yes.

> Or you want to do the test with dosbox and dosbox-x to verify that?

The verification will still help.
At least we can have the proven target
to steal some code from. :)

**Comment by jschwartzenberg** [comment]
Just for reference, two more driver URLs to packages which have a regular OEMSETUP.INF:
SB16 2.3 driver
http://cd.textfiles.com/audio11000/MSDOS/SNDBORDS/SNDBLSTR/SB16W31/SB16W31.EXE

SBPro driver, the wave driver triggers a 'divide by zero' error, but the midi driver works (in standard mode)
http://cd.textfiles.com/audio11000/MSDOS/SNDBORDS/SNDBLSTR/SBP2_W31/SBP2_W31.EXE

**Comment by stsp** [comment]
And in enhanced mode?

**Comment by jschwartzenberg** [comment]
First note bug. I tried a whole bunch of drivers from Vogons actually. The Adlib Gold midi driver also works, but has the same first note bug in enhanced mode. The same with the Windows Resource Kit drivers.
The Windows Sound System drivers do not work at all. Choosing SB16 they show an error that a 386 driver can't be loaded and choosing SB Pro they say an SB Pro cannot be detected.
They are all here: http://www.vogonsdrivers.com/

**Comment by stsp** [comment]
First note bug is curable.
Just needs to implement the timer,
not a big work.

**Comment by jschwartzenberg** [comment]
Alright. I think all FM midi drivers will need this. I just tried the Pro Audio Spectrum one and it has the same first note bug. Note that the SB16 and some other packages have a special Voyetra FM driver. While it works on dosemu in standard mode, it doesn't sound correctly. (In PCEM it does sound correctly.) I guess that's a separate issue though.

**Comment by stsp** [comment]
I still think windows support is a joke.
Why do you think we need all this? :)

**Comment by jschwartzenberg** [comment]
Maybe it's because you only see the problems I report. Of course that's just a small fraction of what I'm testing, as most Windows applications run just fine.
Would it be interesting to have screenshots or maybe even videos of running certain applications in DOSEMU2?

**Comment by stsp** [comment]
Youtube is all for that. :)
Do we run things like msword 6/excel?

**Comment by jschwartzenberg** [comment]
Yes, MS Office runs without issues whatsoever. I tried all programs, they all run great really.

**Comment by jschwartzenberg** [comment]
Not sure if it's relevant, but the SB16 driver installer from here hangs on DOSEMU2:
https://winworldpc.com/download/65c2b8e2-8094-c3b8-11c3-a311c3a7cb86

**Comment by stsp** [comment]
InstallShield?

**Comment by jschwartzenberg** [comment]
No, it's not a Windows-based installer.
