### ISSUE TITLE
Kernel 4.12 slow response in 16 bit mouse applications

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#417]
In Norton Commander, arrow down a large folder. When the mouse is positioned over dosemu the keyboard response is slow and the mouse pointer flickers. Move the mouse away from dosemu and the keyboard response returns to normal.

Response is always fast in the command prompt with no mouse support and Foxpro with mouse support.

Downgrading to 4.9 solves the problem.

**Comment by stsp** [comment]
Try `speed 0`

**Comment by severach** [comment]
I didn't find a speed command but I tried `$_cpuspeed = (0)` and that made it slightly worse without making it any better.

**Comment by stsp** [comment]
You had to because `$_cpuspeed` is not
about that (`$_hogthreshold` is)

**Comment by stsp** [comment]
`speed` command comes with dosemu.

**Comment by andrewbird** [comment]
Putting 'speed' aside for one moment, don't you think it odd that the behaviour varies with kernel version?

**Comment by stsp** [comment]
Maybe, but I defer this till someone else
can confirm the problem. If other people
also clearly attribute it to the kernel version
change and it appears easy to reproduce,
then I will think it is odd and see what can
be done. Checking with `speed 0` is not a
solution, just gathering the necessary info.

**Comment by severach** [comment]
`speed 0` has no effect. It does not slow down or speed up the delay.

It would only be odd if it varied randomly with kernel version. Starting with a certain kernel version only means that they've messed with the video drivers in a way that breaks dosemu.

I just noticed another strange artifact. Move your mouse across some desktop icons. Each icon should highlight and unhighlight as the mouse cursor crosses them. Place dosemu so that it half obscures a desktop icon. Set focus to dosemu with nc running. Hold TAB to generate dosemu activity. Move the mouse across the desktop along some icons into dosemu such that an icon is highlighted as the mouse cursor crosses into the dosemu window. After several tries you see that icon unhighlight is delayed by the same amount that the dosemu window TAB actions are delayed.

Holding down TAB with the mouse over dosemu to cause the delay does not show any excessive CPU usage in htop.

**Comment by stsp** [comment]
Please try `dosemu -X`, `dosemu -t`

**Comment by stsp** [comment]
> means that they've messed with the video drivers in a way that breaks dosemu.

This is only if you use `$_SDL_swrend = (off)`,
which is not a default. We use software rendering
by default, which should not be affected by the
kernel.

**Comment by severach** [comment]
`dosemu -X` and `dosemu -S` slow down equally. `dosemu -t` does not slow down.

**Comment by stsp** [comment]
Can this be reproduced with other programs?
I myself use DN and NDN, not NC.

**Comment by stsp** [comment]
Please provide the `-D9+Xv` log when running `dosemu -X`

**Comment by severach** [comment]
Both crash. ndn_2_31_5309 shows many errors on install like `ERROR: Unimplemented extended open on C:\DN\NDN.DSK` in the Linux window then crashes on run.
````
╔═════════════ Fatal Error ══════════════╗
║                                        ║
║   Exception 0D9h at address 5c3a0003   ║
║                  in ?                  ║
║                 Line 0                 ║
║          Unhandled exception           ║
║           log: C:\DN\NDN.ERR           ║
║           Please report to:            ║
║          email: ---@----.com           ║
║     forum: http://forums.muxe.com/     ║
║                                        ║
╚═══════[ Press any key to exit ]════════╝
````

dn1502 hangs on install leaving a log.
````
VER :DN Install 1.37 Beta
DATE:13 July, 95
ERR :C8
ADDR:04A8011E
PSP :02C2
CS  :0C03
DS  :10EA
SS  :17D1
SP  :3286
MEMm:000842E0
MEMa:000842E0
hOrg:1BD10000
hEnd:9FFF0000
hPtr:1BD10000
hLim:0000
SCR :00000000
````
Both are DPMI programs and should not be affected. 16-bit Borland-C++ 3.1 is affected.

Borland C has long been unusable on 64 bit Linux because it is so slow under 16-bit emulation. 

[boot.log.9XV.zip](https://github.com/stsp/dosemu2/files/1205552/boot.log.9XV.zip)

**Comment by andrewbird** [comment]
@severach the 'Unimplemented extended open' messages are due to the version of DOS you have being PC-DOS/MS-DOS < 4.00 or DR-DOS < 7.00. if you turn off LFN support in dosemu.conf they should go away.
 @stsp Isn't kvm the default on 64bit now?

**Comment by stsp** [comment]
@andrewbird yes, it is.
Log also says `Using V86 mode inside KVM`.
I have no idea what some people say or do. :)

**Comment by severach** [comment]
````
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
````
LFN seems fully supported.

**Comment by andrewbird** [comment]
So that's FreeDOS's kernel.sys you're booting, or just FreeDOS's command.com on top of some other DOS?
The problem comes about because Dosemu redirects LFN open calls to int21/6c and only the versions above those I mentioned have this call.

**Comment by stsp** [comment]
I suppose `-D9+Dd#` will give us some
clue on an 'Unimplemented extended open'
thingy. Preferably in a separate ticket.

**Comment by stsp** [comment]
I think  'Unimplemented extended open' should
now be fixed.

**Comment by stsp** [comment]
Still slow?

**Comment by severach** [comment]
Yes as of 4.13.12. Moving the mouse outside the window has become a regular thing. It's even slow before the window can be seen, when the mouse is above where Cinnamon will animate up then paint the window. Same as before. Slow in emulated 16 bit NC, fast in native 32 bit Foxpro.

**Comment by stsp** [comment]
Repeating older comment,

Can this be reproduced with other programs? I myself use DN and NDN, not NC.

**Comment by severach** [comment]
Does not happen: ndn, dn, Norton Utilities, Foxpro

Does happen: Borland C++ 3.1, nc 4.0, nc 5.5, vc, DOSZIP Commander, Laplink ll3

**Comment by stsp** [comment]
`In Norton Commander, arrow down a large folder.`
And how the one is supposed to do "large folder" stuff
in bc3.1? Please record a video.

**Comment by severach** [comment]
Anything that causes the screen to paint goes slow and makes the mouse flicker. In BC you can just hold a key down in the editor.

No video can capture the flickering mouse.

**Comment by stsp** [comment]
I don't need to capture flickering of the
mouse - bc and others just switch off the
mouse cursor while updating the text
screen, so it flickers a bit.
I want to see
```
When the mouse is positioned over dosemu the keyboard response is slow
```
How can I measure it is slow?

**Comment by severach** [comment]
[DSCF4731.mp4.gz](https://github.com/stsp/dosemu2/files/1490073/DSCF4731.mp4.gz)

Norton Commander 5.5
Non client area: fast
Client area: slow and mouse flickers.

This seems ok because only a few characters are being painted on each change. It freezes for a few seconds when the entire screen is painted.

**Comment by stsp** [comment]
Could you please run htop and see if
there is something wrong with CPU usage
when it is slow? Does it use 100% of CPU,
or just sleeps?

**Comment by severach** [comment]
There is no excessive CPU usage even when I use ^O in `nc` to repaint the whole screen.

**Comment by stsp** [comment]
Try Ctrl-Alt-home to activate the mouse grab.

**Comment by severach** [comment]
The speed problem is not present while the mouse is captured.

**Comment by stsp** [comment]
In `sdl.c` try to comment the line 949,
`SDL_ShowCursor()`

**Comment by severach** [comment]
That eliminates the speed problem. ^O runs as fast as possible.

**Comment by stsp** [comment]
In `X.c` please comment lines 1237 and 1247,
and see if that helps with `dosemu -X`. If so,
please check which one exactly of those makes
the problem.

**Comment by severach** [comment]
Commenting out either one or both fixes it. Commenting only 1237 makes the mouse invisible while in the `dosemu -X` window. Commenting out 1242 or both leaves the mouse visible as expected. `dosemu` (SDL) is always slow and not affected by these changes.

**Comment by stsp** [comment]
The for some reason `XDefineCursor()` became
slow for you. You can report this to Xorg bugzilla,
but you would need to write a small test-case.

**Comment by severach** [comment]
It changed from kernel 4.11 to 4.12 and continues with 4.13. Seems like a breaking user space problem to me. It will be slow for everyone when they get there.

**Comment by stsp** [comment]
Can you create a small test-case from
the snippets of `X.c`?

**Comment by severach** [comment]
Turns out Foxpro is affected. USE DB, bring up a browse window, and move the columns around with the mouse. In 4.9LTS the columns move as expected whether the mouse is captured or not. In 4.13 the columns move very slowly if the mouse is not captured.

**Comment by stsp** [comment]
Anything that hides mouse during the text
update, is "affected". This is all info we need
to know. The rest is to write a small test-case
that hides/unhides the mouse in a loop, and
send it to the right people.

**Comment by stsp** [comment]
Interestingly, right now the ubuntu updater
offered me to install the critical security updates
with the only one item: X cursor management library!
I hope this critical bug is now fixed. :)

**Comment by stsp** [comment]
Is this still happening?

**Comment by severach** [comment]
This is still a problem. I regularly move the mouse outside the window or boot to kernel 4.9 to avoid it completely.

ndn and dn are affected. The mouse flickers in 4.18 and doesn't in 4.9. They have better mouse handling than nc so it's hard to see. It can be seen by holding ^O and moving the mouse in and out of the window. There is a slight change in display speed in 4.18 that doesn't happen in 4.9.

Something nc is doing with the mouse makes the problem really bad.

**Comment by stsp** [comment]
I don't think its kernel itself, but rather some
kernel option that archlinux changed. Not for
the first time btw.
You can probably try 4.9 config on 4.10 and
vice versa, to see if that changes something.

**Comment by stsp** [comment]
Native mouse is now hidden in NDN.
Does the problem persist with NDN, and
does it persist with other software?
