### ISSUE TITLE
dosdebug: Question about Dosemu symbols

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#471]
So on a local side project I'm experimenting with tweaks to dosdebug, that if good enough hopefully could be integrated back into Dosemu2. I notice that dosdebug loads the dosemu.bin symbols at startup
~~~
Reading map file nm /clients/common/dosemu2.git/2.0-pre7/bin/dosemu.bin | grep -v '\(compiled\)\|\(\.o$\)\|\( a \)' | sort
7787 symbol(s) processed
highest address 019bb050(_end)
dosdebug> 
~~~
I've never noticed where these symbols get used, and also wonder if that means dosdebug could step into 32bit code. Can anyone enlighten me?

**Comment by stsp** [comment]
> So on a local side project I'm experimenting with tweaks to dosdebug,

Which ones and how do they relate to dosemu.map?

> I've never noticed where these symbols get used, and also wonder
> if that means dosdebug could step into 32bit code.

It was most likely for bios.S.
But today the addresses do not match
so they should be offsetted for this to work
again. I guess some very old dosemus had
a separate ELF entry for bios (or, likely, it
was not even ELF but a-out) that was mapped
directly to DOS addresses, so this could work.
To the date we have more relocation levels
than the one could ever desire. :)

**Comment by andrewbird** [comment]
> Which ones and how do they relate to dosemu.map?

Actually only very loosely. I mentioned before that I'd switched dosdebug from pipes to unix socket to avoid the lossy transfer. I followed your suggestion to have tracing whilst waiting for key press log to a file and that solved the interactivity problem. I implemented this by opening the file in the dosdebug client and then pass the open descriptor over the socket. This meant i could run dosemu as root if necessary and it still function over NFS with root squashing, files were always owned by the client's user and their location relative to the client. Finally I was looking at other dosdebug commands that use files, which included `rmapfile`, to see if it was worth doing the same file descriptor passing technique for those. So in reality I wondered if I was missing some great feature of dosdebug :smile: 

Current tweaks include:
 - make debugger use unix domain sockets (can use abstract sockets on Linux)
 - make debugger use gnu readline (command recall, history, completion, help etc)
 - make debugger optionally use tracefile.

BTW I came across [capstone](https://github.com/aquynh/capstone) which looks interesting

**Comment by andrewbird** [comment]
Thanks for the info, closing.

**Comment by stsp** [comment]
> I implemented this by opening the file in the dosdebug client and
> then pass the open descriptor over the socket.

Uugh!
While I see your point on making this
still owned by client, I wonder if this is
really impossible to do otherwise, for
example by creating the file by client
first, and pass its name to the server
next. Of if you did it that way, please
don't spread that to other things like
rmapfile. :) "tc" is really special by
having the nasty speed requirements,
so there is no need to unify things with
it.

> BTW I came across capstone which looks interesting

You mean instead of udis86?

Readline looks like a cool enhancement,
and what does trace file does? The script
that passes the command to dosdebug?

**Comment by andrewbird** [comment]
> I wonder if this is really impossible to do otherwise, for example by creating the file by client
first, and pass its name to the server next.

What you describe is how 'dump' is implemented within dosdebug. Probably it's only me that cares about operation with NFS root squashing, but unless dosemu and dosdebug are running as the same user, passing filenames for dosemu to write will require either wide open file permissions or g+w and group membership, plus execute and maybe read bits on all the directories in the path to it. Passing open file descriptors between processes over a unix domain socket is for exactly this purpose.

> You mean instead of udis86

Yep, as well as writing the pretty string in Intel or AT&T format, the instruction detail is accessible. Perhaps that will allow us to add annotations indicating the values of memory locations referenced in the instruction operands.

This little test prog disassembles one instruction which seems quite easy.
```C
#include <inttypes.h>
#include <stdio.h>

#include <capstone/capstone.h>

uint8_t CODE[] = {
  0x26, 0x8F, 0x06, 0x2E, 0x00, // pop		word ptr es:[0x2e]

  /* trailing crap */
  0x05, 0x06, 0x07, 0x08, 0x09,
  0x0a, 0x0b, 0x0c, 0x0d, 0x0e
};

int main(void)
{
  csh handle;
  cs_insn *insn;
  size_t count;

  if (cs_open(CS_ARCH_X86, CS_MODE_16, &handle) != CS_ERR_OK)
    return -1;
//  cs_option(handle, CS_OPT_SYNTAX, CS_OPT_SYNTAX_ATT);
  count = cs_disasm(handle, CODE, 15, 0x1000, 0, &insn); // 15 is max length x86 instruction
  if (count > 0) {     // just the first instruction
    printf("0x%" PRIx64 ":\t%s\t\t%s\n", insn[0].address, insn[0].mnemonic,  insn[0].op_str);
    cs_free(insn, count);
  } else
    printf("ERROR: Failed to disassemble given code!\n");

  cs_close(&handle);
  return 0;
}
```

I was thinking of using the created tracefile as input to a database of instructions and data accesses that which might make visualising what a program was doing easier. But for now it's just great that no data is dropped and 'tc' can be stopped instantaneously.

**Comment by stsp** [comment]
I'd say udis86 also can print pretty
string, considering their example on
the main page:
```
$ echo "65 67 89 87 76 65 54 56 78 89 09 00 87" | udcli -32 -x
0000000000000000 656789877665    mov [gs:bx+0x6576], eax
0000000000000000 54              push esp
0000000000000000 56              push esi
0000000000000000 7889            js 0x93 
0000000000000000 0900            or [eax], eax
```
But I will not force you into any decision.
I just think udis86 is more frequently used.

**Comment by andrewbird** [comment]
Playing a little more with capstone I see that it doesn't handle segments. So computed things like jump short/long targets aren't correct. There's a three year old issue https://github.com/aquynh/capstone/issues/111 but no fix. The nearest I got to fudging it was to ignore the segment and just pretend the instruction to be disassembled was at 0000:offset, which sort of worked, but won't deal with wrapping.
`0070:0010 jmp	0x13` # segment:offset printed by hand, then eb01 disassembled
same instruction but offset is close to segment boundary
`0070:fffe jmp	0x10001`

I suppose it's possible by intercepting all the jumps etc and writing the segment:offset output manually, but that negates the cool ATT / Intel syntax switching feature...

**Comment by stsp** [comment]
Maybe its time to try out udis86? :)

**Comment by andrewbird** [comment]
Same test with udis86
```
$ echo "EB 01" | ./udcli -16 -x -o 0
0000000000000000 eb01             jmp 0x3

$ echo "EB 01" | ./udcli -16 -x -o fffe
000000000000fffe eb01             jmp 0x1
```

So wrapping seems to be sorted for near jumps (simple & 0xffff), but from what I can see in the code it has no support for display of seg:ofs etc.

I checked out radare2 - wow! Whilst it uses capstone, it does implement the seg:ofs itself. I see that radare2 implements debugger plugins, I wonder what's required to make it talk to dosdebug.

**Comment by stsp** [comment]
So what exactly is a problem?
You want the seg:offs address to be printed
even for short jumps? Is it really necessary?

**Comment by andrewbird** [comment]
Not a problem, but it means whether I use udis86 or capstone, I need to format the output myself to 
`xxxx:yyyy jmp zzzz` which wasn't my original goal. Have you looked at radare2, for a text based tool it has lots of features for visualising what a program is doing?

**Comment by stsp** [comment]
I didn't know writing `xxxx:yyyy` by hands
and only using disasm for `jmp zzzz` is such
a big deal. In fact its natural unless the disasm
has an access to our internal register state.
Or maybe you can only write `xxxx:` by hands
and have the disasm to write `yyyy jmp zzzz`?

**Comment by andrewbird** [comment]
So getting back to the usefulness of unix symbols in dosdebug. Am I right in thinking that it's only those in bios.S that are potentially useful? I wonder if we can generate DOS seg:ofs values from bios.o, include them in a debugger map file and subsequently kill dosdebug's unix addressing mode?

~~~
$ nm ./src/base/bios/bios.o | sort -n | grep ipx_handler
0000e310 t ipx_handler
~~~
~~~
$ nm 2.0-pre7/bin/dosemu.bin | grep ipx_handler
0011fe10 t ipx_handler
~~~

The comments suggest the code is installed in DOS at F800:6310
```asm
/* ----------------------------------------------------------------- */         
        .org    ((IPX_SEG - BIOSSEG) << 4) + IPX_OFF                            
/* ======================= Addr = F800:6310 (FE310) */                          
ipx_handler:                                                                    
        int     $0x7a                                                           
        lret                                                                    
```

The disassembly in dosdebug confirms it
~~~
u F800:6310

f800:6310 CD7A             int  7A
f800:6312 CB               retf
<snip>
~~~

So is there a generic way to convert from `nm bios.o` to a bios.map file address?

**Comment by stsp** [comment]
> Am I right in thinking that it's only those in bios.S that are potentially useful?

I _think_ so, but its not me who wrote
that and I haven't ever seen it working,
so only guesses. In either case, we are
free to make it our way.
Note that in DPMI there is also dpmisel.S
whose code is exported to DOS and since
dosdebug supports prot mode, this can
be used for symbols too.

> I wonder if we can generate DOS seg:ofs values
> from bios.o, include them in a debugger map file
> and subsequently kill dosdebug's unix addressing mode?

I had a simple plan in mind to kill only `mode`
_command_ rather than to eradicate linear
addresses everywhere. If we kill the `mode`
command, then we are free to interpret the
addresses according to their context: user
input should be treated in some way, and
addresses from .map should be treated in
another way, and there will be no question
"what mode is now and how to proceed".

**Comment by andrewbird** [comment]
No, I didn't want to eradicate linear addresses totally. I agree about killing the mode command, but since the linear addresses can be dos or unix I figured getting rid of the unix ones would be good idea. Although the unix symbols don't appear to work at present, i've never seen them in dosdebug, the idea behind them seems fine. I thought having them loaded as DOS symbols might be nice, not necessarily from an external .map file, but at the correct seg:ofs. is it possible to determine that address from bios.o?

**Comment by stsp** [comment]
So basically you ask how to convert the
unix addresses _properly_? Well, instead
of doing it properly, we can at first do it
_somehow_, namely, to just use 0xf000
as the bios segment, and calc offsets
relatively to this.
And as for how to convert unix addr to
linear DOS addr - just subtract bios_fooo
address from unix address.

**Comment by andrewbird** [comment]
Incidentally it seems that unix addresses do work

The bios.S code
~~~
u ipx_handler

0000:00000000 CD7A             int  7A
0000:00000002 CB               retf
0000:00000003 0000             add  [eax],al
0000:00000005 0000             add  [eax],al
0000:00000007 0000             add  [eax],al
0000:00000009 0000             add  [eax],al
0000:0000000b 0000             add  [eax],al
0000:0000000d 0000             add  [eax],al
0000:0000000f 0006             add  [esi],al
0000:00000011 57               push edi
0000:00000012 50               push eax
0000:00000013 B80C12CD2F       mov  eax,2FCD120C
0000:00000018 58               pop  eax
0000:00000019 5F               pop  edi
0000:0000001a 07               pop  es
0000:0000001b CF               iret
0000:0000001c 0000             add  [eax],al
0000:0000001e 0000             add  [eax],al
~~~

A real unixland function
~~~
u mhp_disasm

0000:00000000 55               push ebp
0000:00000001 57               push edi
0000:00000002 56               push esi
0000:00000003 53               push ebx
0000:00000004 81EC0C010000     sub  esp,0000010C
0000:0000000a 8BB42420010000   mov  esi,[esp+00000120]
0000:00000011 8BBC2424010000   mov  edi,[esp+00000124]
0000:00000018 65A114000000     mov  eax,gs:[00000014]
0000:0000001e 898424FC000000   mov  [esp+000000FC],eax
~~~

But I also note that it seems to not care if the symbol actually exists and unassembles something

~~~
u fred

0000:000f F006             lock push es
0000:0011 C000F0           rol  byte [bx+si],F0
0000:0014 07               pop  es
0000:0015 C000F0           rol  byte [bx+si],F0
0000:0018 08C0             or   al,al
0000:001a 00F0             add  al,dh
0000:001c 09C0             or   ax,ax
0000:001e 00F0             add  al,dh
0000:0020 A5               movsw
0000:0021 7E00             jle  0023 ($+0)
0000:0023 F8               clc
0000:0024 87E9             xchg cx,bp
0000:0026 00F0             add  al,dh
0000:0028 00F1             add  cl,dh
0000:002a 00F0             add  al,dh
0000:002c 0DC000           or   ax,00C0
u fakefreddy

000f:000a 00F0             add  al,dh
000f:000c 41               inc  cx
000f:000d C000F0           rol  byte [bx+si],F0
000f:0010 42               inc  dx
000f:0011 C000F0           rol  byte [bx+si],F0
000f:0014 016400           add  [si],sp
000f:0017 F8               clc
000f:0018 44               inc  sp
000f:0019 C000F0           rol  byte [bx+si],F0
000f:001c 6A17             push 0017
000f:001e 00C0             add  al,al
000f:0020 46               inc  si
000f:0021 C000F0           rol  byte [bx+si],F0
000f:0024 47               inc  di
000f:0025 C000F0           rol  byte [bx+si],F0
000f:0028 206400           and  [si],ah
~~~

**Comment by stsp** [comment]
```
u mhp_disasm

0000:0000 0000             add  [bx+si],al
0000:0002 0000             add  [bx+si],al
0000:0004 0000             add  [bx+si],al
0000:0006 0000             add  [bx+si],al
0000:0008 0000             add  [bx+si],al

u ipx_handler
[ crash ]
```

Hmm?

**Comment by andrewbird** [comment]
Perhaps it only works in 32bit?

**Comment by andrewbird** [comment]
Crashes for me on 64bit too. I notice that the value of ipx_handler(and other nm symbols) is very different
~~~
$ nm 2.0-pre7/bin/dosemu.bin| grep ipx_handler
00000000001263b0 t ipx_handler
~~~

It blows up when trying to access memory up there, and I think that value is the key.

I also notice that some of the code (mhp_dump, mhp_disasm) is checking for seg == 0 as an indicator of unix linear address. Since I started setting normalized values to ease the problems in #494 that's probably not valid any more. I don't think it started this crash issue as 32bit's okay and I think you saw it before then on 64bit.

**Comment by stsp** [comment]
> It blows up when trying to access memory up there, and I think that value is the key.

Hmm, try to remove `-fpie -pie` from configure.ac.
With pie, these addresses are all meaningless.

**Comment by stsp** [comment]
I think dosemu symbols should be resolved
via dlsym() or something like that. Though I
wouldn't be surprised if with pie dlsym() would
just return the PLT entry addr.

**Comment by andrewbird** [comment]
after removing the -fpie -pie from configure.ac
~~~
$ nm bin/dosemu.bin | grep ipx_handler
0000000000512a10 t ipx_handler
~~~
but it still crashes on `u ipx_handler`

**Comment by stsp** [comment]
u mhp_disasm?

**Comment by andrewbird** [comment]
I tried dlopen/dlsym on the executable
```C
@@ -283,8 +285,22 @@ static char * getname2u(unsigned int addr)
 static unsigned int getaddr(const char *n1, unsigned int *v1)
 {
    int i;
+   char *p;
+
    if (strlen(n1) == 0)
       return 0;
+   if (strcmp("ipx_handler", n1) == 0) {
+      p = dlopen(NULL, RTLD_LAZY);
+      if (!p) {
+             mhp_printf("dlopen failed\n");
+             return 0;
+      }
+      *v1 = (unsigned int) dlsym(p, n1);
+      if(!*v1)
+             mhp_printf("dlerror: %s\n", dlerror());
+      dlclose(p);
+      return 1;
+   }
    for (i=0; i < last_symbol; i++) {
```
but I got
~~~
dosdebug> u ipx_handler
dosdebug> 
dlerror: bin/dosemu.bin: undefined symbol: ipx_handler
~~~

And the same for mhp_disasm (with code tweak)

**Comment by stsp** [comment]
> but it still crashes on u ipx_handler

ipx_handler should be simple, you just need to
subtract bios_f000 from the addr.
u mhp_disasm may probably be fixed w/o pie.

**Comment by stsp** [comment]
IIRC to get dlsym working, you need `-rdynamic`.
OTOH I don't believe in dlsym, it will not go further
than to PLT.

**Comment by andrewbird** [comment]
Not sure fixing d/u of mhp_disasm() etc is useful anyway.  Regarding ipx_handler - bios_addr, why isn't this necessary in 32 bit?

~~~
$ nm bin/dosemu.bin | grep bios_f000
0000000000118140 T bios_f000
$ nm bin/dosemu.bin | grep ipx_handler
0000000000126450 t ipx_handler

$ python
>>> hex(0x0000000000126450-0x0000000000118140)
'0xe310'
~~~

And looking directly at bios.o
~~~
$ nm src/base/bios/bios.o | egrep -w '(bios_f000|ipx_handler)'
0000000000000000 T bios_f000
000000000000e310 t ipx_handler
~~~


so I added this code
```C
+++ b/src/tools/debugger/mhpdbgc.c
@@ -283,8 +283,26 @@ static char * getname2u(unsigned int addr)
 static unsigned int getaddr(const char *n1, unsigned int *v1)
 {
    int i;
+   uint16_t x;
+   char *p;
+
    if (strlen(n1) == 0)
       return 0;
+   if (strcmp("ipx_handler", n1) == 0) {
+
+      x = 0xe310; // assume we built this in at build time
+
+      p = (char *)bios_f000;
+      p += x;
+
+      mhp_printf("pointer is %p\n", p);
+
+      *v1 = (unsigned int) p;
+
+      mhp_printf("value is %x\n", *v1);
+
+      return 1;
+   }
```


and the result
~~~
pointer is 0x55dad1d4d380
value is d1d4d380
~~~

Isn't it a problem that on 64 bit my pointers can't be wholly contained in an unsigned int?

**Comment by stsp** [comment]
> Regarding ipx_handler - bios_addr, why isn't this necessary in 32 bit?

Maybe because just today I've removed -fpie? :)

> Isn't it a problem that on 64 bit my pointers can't be wholly contained in an unsigned int?

But not w/o pie. You have returned -pie surely.

**Comment by andrewbird** [comment]
Yep I reinstated -pie here

**Comment by andrewbird** [comment]
Okay I removed -pie again, and if forcing mhp_dump to see it as a unix address I can dump ipx_handler
~~~
dosdebug> d ipx_handler
dosdebug> 
pointer is 0x5129d0
value is 5129d0

5129d:0000 CD 7A CB 00 00 00 00 00 00 00 00 00 00 00 00 00  MzK.............
5129d:0010 06 57 50 B8 0C 12 CD 2F 58 5F 07 CF 00 00 00 00  .WP8..M/X_.O....
5129d:0020 2E 80 3E 08 50 01 74 38 08 E4 74 08 3D 02 4F 75  ..>.P.t8.dt.=.Ou
5129d:0030 2F 53 EB 01 50 50 53 B8 33 00 BB F0 00 CD E6 5B  /Sk.PPS83.;p.Mf[
5129d:0040 58 66 0F B7 E4 67 FF 74 24 06 0E E8 12 00 50 53  Xf.7dgt$..h..PS
5129d:0050 B8 33 00 BB F1 00 CD E6 5B 58 83 C4 02 CA 02 00  83.;q.Mf[X.D.J..
5129d:0060 2E FF 2E 04 50 00 00 00 00 00 00 00 00 00 00 00  ...P...........
5129d:0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
~~~

```C
diff --git a/src/tools/debugger/mhpdbgc.c b/src/tools/debugger/mhpdbgc.c
index 7d32cff..56d1da6 100644
--- a/src/tools/debugger/mhpdbgc.c
+++ b/src/tools/debugger/mhpdbgc.c
@@ -283,8 +283,26 @@ static char * getname2u(unsigned int addr)
 static unsigned int getaddr(const char *n1, unsigned int *v1)
 {
    int i;
+   uint16_t x;
+   char *p;
+
    if (strlen(n1) == 0)
       return 0;
+   if (strcmp("ipx_handler", n1) == 0) {
+
+      x = 0xe310; // assume we built this in at build time
+
+      p = (char *)bios_f000;
+      p += x;
+
+      mhp_printf("pointer is %p\n", p);
+
+      *v1 = (unsigned int) p;
+
+      mhp_printf("value is %x\n", *v1);
+
+      return 1;
+   }
    for (i=0; i < last_symbol; i++) {
       if (strcmp(symbol_table[i].name, n1) == 0) {
          *v1 = symbol_table[i].addr;
@@ -707,6 +725,7 @@ static void mhp_dump(int argc, char * argv[])
 #endif
    if (IN_DPMI && seg) data32=dpmi_mhp_get_selector_size(seg);
    unixaddr = linmode == 2 && seg == 0 && limit == 0xFFFFFFFF;
+   unixaddr = 1;
    for (i=0; i<nbytes; i++) {
       if ((i&0x0f) == 0x00) {
          if (seg != 0 || limit != 0xFFFFFFFF) {
```
Questions:
- Will you remove -pie permanently, what's the downside?
- Any point in having unix linear u/d capability for symbols outside bios.S/dpmisel.S?
- Unixaddr in mhp_disasm is set by checking linmode == 2 && seg == 0, neither is true in the `d ipx_handler` case.

**Comment by stsp** [comment]
> +      p = (char *)bios_f000;

You likely don't even need this w/o pie.
You can probably directly access unix
addresses from map.

> Will you remove -pie permanently, what's the downside?

Not from x86_64. The downside is too low
default address, plus pie-compatible code is
more "portable" - I mean distros that force
pie for security reasons etc. Plus we must
be prepared to handle the relocatable code
rather than to stick on a fixed memory layouts
that suits our needs today - memory layouts
tend to change, and we already were bitten
by this many times. So it is better to support
non-fixed layout from day 1.

> Any point in having unix linear u/d capability for symbols outside bios.S/dpmisel.S?

No idea, really. I.e. it would be totally
crazy to set a break-point to the dosemu
func with dosdebug, but if `u` already works
or almost - why not to resurrect it just for fun? :)

> neither is true in the d ipx_handler case.

Likely w/o pie you can handle them the same
way. But with pie we are of course stuck to
bios-only symbols plus bios_fooo relocation.

**Comment by stsp** [comment]
Note that w/o pie, the dosemu code resides
in the lower 4Gb, so is visible to the DOS.
With pie it resides in a completely different
universe that DOS can never observe. I
don't think this is a big security benefit as
dosemu provides enough bridges to the
host system anyway, but it looks like the
design advantage.

**Comment by andrewbird** [comment]
I checked and yes you are correct that `u ipx_handler` was fixed by the removal of -pie on 32bit.

> No idea, really. I.e. it would be totally
crazy to set a break-point to the dosemu
func with dosdebug

I may be wrong, but unless that dosemu symbol is from bios.S or dpmisel.S the debugger would never traverse it and break? GDB would be best for breaking/examining dosemu itself I suppose, or am I missing something?

I'm wondering about the normalised seg:off representation for dos linear addresses that I just added to help with #494. Unless the linear address is <= 0x10ffef, surely the calculated seg:ofs must be rubbish?
Doesn't an address > 0x10ffef mean it should be represented in a protected mode form (warning: my knowledge here is very limited - is that LDT?)

**Comment by stsp** [comment]
> I may be wrong, but unless that dosemu symbol is from bios.S or
> dpmisel.S the debugger would never traverse it and break?

Yes, I meant just in theory. Therefore we are not
going to implement that kind of things, but maybe
it is possible to not remove what is already there.
But at the end of the day it doesn't matter much. :)

You can use `mode +d/-d` to enable/disable
protected mode addressing. If linear address
exceeds lowmem+hma and we are in real mode
addressing, you can either error out, or, if we
mess around unix fns & non-pie - interpret it
as unix address. Well, I guess perhaps just
dropping this unix stuff would be simpler. :)

**Comment by stsp** [comment]
```
+   if (strcmp("ipx_handler", n1) == 0) {
+
+      x = 0xe310; // assume we built this in at build time
+
+      p = (char *)bios_f000;
+      p += x;
+
+      mhp_printf("pointer is %p\n", p);
+
+      *v1 = (unsigned int) p;
```

This is actually the wrong way.
Try just `v1 = READ_DWORD(0xfe310)`.

**Comment by andrewbird** [comment]
So does bios_f000 address the exact same memory as appears at f000:0000 to DOS? Perhaps it is a copy as I do see the correct instruction bytes at bios_f000+0xe310.
My ideal would be to kill the unix address d/u, but process bios.o somehow to create the correct seg:offsets for the symbols within, so that `u ipx_handler` resolves to `F800:6310`

**Comment by stsp** [comment]
> Perhaps it is a copy

Indeed, that's why it works. And for
purely unix funcs this is the only way
we have (no copy in DOS space), but
for bios.S we should use copy as only
there we can put breakpoints.

> My ideal would be to kill the unix address d/u

OK, as soon as it seems to be not possible
to resurrect quickly because of pie...
By the way, pie defines macros like
__PIE__ so maybe kill it conditionally?
Anyway, up to implementer.

> but process bios.o somehow to create
> the correct seg:offsets for the symbols
> within, so that u ipx_handler resolves to F800:6310

I don't see why not to resolve this at run-time.
All you need is to subtract bios_foo then add
0xf0000.

**Comment by stsp** [comment]
And as for `d` - feel free to kill it for
unix addresses for sure. I only a bit
pity about `u` as it seems to be almost
working, but there is no real need indeed.
