### ISSUE TITLE
dosemu -t terminal mode crashes on mouse movement

### ISSUE THREAD

**Issue by severach** [stsp/dosemu2#574]
Moving the mouse outputs mouse codes to the screen and after about 8 codes dosemu2 crashes. The crash is the same whether in a mouse program like `nc` or a non mouse DOS prompt.

````
ERROR: Accessing reserved memory at 322c434d5b1b
<>Maybe a null segment register
````

The mouse used to work in terminal mode. I've tried old versions for kernel and dosemu2.

**Comment by stsp** [comment]
Please attach `~/.dosemu/boot.log`

**Comment by severach** [comment]
[boot.log.terminal.zip](https://github.com/stsp/dosemu2/files/1782954/boot.log.terminal.zip)

**Comment by stsp** [comment]
Should now be fixed.

**Comment by severach** [comment]
The crashing has stopped but the mouse doesn't work and the mouse characters are still showing up on the screen. Here's are some sample characters sequences.

````
MC1(MC3'MC6'MCA#CA*MH.MCCCF)MCF)MC?+,MC8,MC3-MC3.MC0/C-/MMC*/-+,MC+,C0C9,MC:,MC<-=.MC=MC=/MC=MC=MG=/MG=/MG</:2
MCc"MC`"MC^#MC[#MCU$MCS$MCP$MCN%MCL%MCJ%MCH%MCD%MCC&MCA&MC@&MC?&MC?&MC>&MC
````

**Comment by severach** [comment]
The crashing has stopped but the mouse doesn't work and the mouse characters are still showing up on the screen. Here's are some sample characters sequences.

````
MC1(MC3'MC6'MCA#CA*MH.MCCCF)MCF)MC?+,MC8,MC3-MC3.MC0/C-/MMC*/-+,MC+,C0C9,MC:,MC<-=.MC=MC=/MC=MC=MG=/MG=/MG</:2
MCc"MC`"MC^#MC[#MCU$MCS$MCP$MCN%MCL%MCJ%MCH%MCD%MCC&MCA&MC@&MC?&MC?&MC>&MC
````

**Comment by stsp** [comment]
Nothing have recently changed wrt mouse.
The crasher you've found, was very old (from
when this code was initially written in 2002).
So if you can find when this stopped to work
for you, please open another ticket and specify
the revision number.
