### ISSUE TITLE
compiler warnings and errors

### ISSUE THREAD

**Issue by requiredregistration** [stsp/dosemu2#779]
gcc 8.2.1
```
snd_o_ao.c: In function ‘aosnd_open’:
snd_o_ao.c:88:13: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     opt.key = "buffer_time";
             ^
snd_o_ao.c:89:15: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     opt.value = "40";
               ^
```
```
X.c: In function ‘X_init’:
X.c:728:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   xch.res_name  = "XDosEmu";
                 ^
X.c:729:17: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
   xch.res_class = "XDosEmu";
                 ^
```

clang 7.0.1
```
disks.c:1360:8: warning: variable 'dp' is uninitialized when used here [-Wuninitialized]
    if(dp->type == DIR_TYPE) {
       ^~
../../../src/include/disks.h:178:9: note: expanded from macro 'FOR_EACH_HDISK'
        c \
        ^
disks.c:1353:18: note: initialize the variable 'dp' to silence this warning
  struct disk *dp;
                 ^
                  = NULL
1 warning generated.
```
```
fatfs.c:1569:7: warning: variable 'idx' is used uninitialized whenever '||' condition is true [-Wsometimes-uninitialized]
  if (!f || (idx = sys_file_idx(f->obj[1].name, f)) == -1) {
      ^~
fatfs.c:1573:17: note: uninitialized use occurs here
  if (f->sfiles[idx].pre_boot)
                ^~~
fatfs.c:1569:7: note: remove the '||' if its condition is always false
  if (!f || (idx = sys_file_idx(f->obj[1].name, f)) == -1) {
      ^~~~~
fatfs.c:1562:20: note: initialize the variable 'idx' to silence this warning
  int fd, size, idx;
                   ^
                    = 0
1 warning generated.
```
```
builtins.c:638:26: warning: result of comparison of constant 256 with expression of type 'unsigned char' is always true [-Wtautological-constant-out-of-range-compare]
        assert(psp->cmdline_len < sizeof(cmdbuf)); // len uint8_t, cant assert
               ~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~
/usr/include/assert.h:106:11: note: expanded from macro 'assert'
      if (expr)                                                         \
          ^~~~
1 warning generated.
```
```
bootnorm.S:36:27: error: unexpected token in argument list
                jmp 0x1FE0:0x7c00+ cont-real_start
                          ^
bootnorm.S:61:21: error: unknown token in expression
                jmp $
                    ^
bootnorm.S:89:33: error: unknown token in expression
                cmp word ptr [es:0x7c00+0x1fe],0xaa55
                                ^
bootnorm.S:96:24: error: unexpected token in argument list
                jmp 0x0:0x7c00 # and jump to boot sector code
                       ^
bootnorm.S:122:19: error: cannot use more than one symbol in memory operand
        jmp short LBABios
                  ^
bootnorm.S:154:36: error: unknown token in expression
        mov [0x7c00+ (_bios_LBA_low-real_start)],ax
                                   ^
bootnorm.S:156:37: error: unknown token in expression
        mov [0x7c00+ (_bios_LBA_high-real_start)],ax
                                    ^
bootnorm.S:159:45: error: unknown token in expression
    mov si,0x7c00+ (_bios_LBA_address_packet-real_start)# regs.si = FP_OFF(&dap)#
                                            ^
make[2]: *** [/root/dosemu2/src/Makefile.common:91: bootnorm.o] Error 1
make[1]: *** [/root/dosemu2/src/arch/linux/Makefile.main:111: plugin/periph] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:25: default] Error 2
```

**Comment by stsp** [comment]
Thanks.
Should now be fixed.

**Comment by requiredregistration** [comment]
partially.

the things gcc warns about were not fixed, and clang still fails to compile it because of the bootnorm.S errors.

**Comment by stsp** [comment]
@andrewbird would you like to convert
`bootnorm.S` into `bootnorm.s` by not linking
it into mkfatimage16?

**Comment by andrewbird** [comment]
Okay, but not much time this week. I'll try to do it this morning.

**Comment by stsp** [comment]
No rush, thank you. :)

**Comment by andrewbird** [comment]
Added PR #780

**Comment by stsp** [comment]
Thanks!
I confirm that clang build now works again.
Hope it will stay so for some time. :)
