### ISSUE TITLE
ERROR: Bootable drive not found, exiting

### ISSUE THREAD

**Issue by ZoccoCss** [stsp/dosemu2#783]
**Describe the bug**
I made a fresh install from the Ubuntu repository. The first screen asks to press enter to boot Dosemu. After that the window closes and give the ERROR: Bootable drive not found, exiting. I tried to run the program again and got the same message. 

I unistalled dosemu and fdpp and made a rm -rf ~/.dosemu  to get a new fresh install. I repeated the instalation process and got the same error. 

**To Reproduce**
Make a fresh install 

**Attach the binaries
None in this case

**Attach the log**
CONF: config variable parser_version_3 set
CONF: config variable c_system set
CONF: Parsing built-in dosemu.conf file.
CONF: config variable version_3_style_used set
CONF: Parsing built-in global.conf file.
CONF: config variable version_3_style_used unset
CONF: config variable version_3_style_used set
CONF: opened include file /etc/dosemu/dosemu.conf
CONF: closed include file /etc/dosemu/dosemu.conf
CONF: mapping driver = 'auto'
debug flags: -a+cw
CONF: Disabling use of pentium timer
CONF: dosbanner on
CONF: timer freq=18, update=54925
CONF: CPU set to 586
CONF: JIT CPUEMU set to 0 for 586
CONF: CPU VM set to -1
CONF: CPU VM set to -1 for DPMI
CONF: 8192k bytes EMS memory
CONF: EMS-frame = 0xe000
CONF: DPMI-Server on (0x20000)
CONF: DPMI linear reserve base addr = 0xffffffff
CONF: DPMI linear reserve size = 0x8000
CONF: PM DOS API Translator on
CONF: No DJGPP NULL deref checks: on
CONF: 8192k bytes XMS memory
CONF: dosemu not running on console
CONF: time mode = 'bios'
SER: directory /var/lock namestub LCK.. binary No
MOUSE: /dev/input/mice, type 7 using internaldriver: yes, emulate3buttons: no baudrate: 0
CONF: Keyboard-layout keyb-user
ERROR: drive C: no device/file-name given!
CONF: disk type 'Directory' drive C:
CONF: **** Warning: floppy /dev/fd0 not accessible, disabled
CONF: fastfloppy = 1
CONF: cdrom MSCD0001 on /dev/cdrom
CONF: IPX support off
CONF(LPT0) f: (null)   c: lpr -l  t: 20  port: 0
CONF(LPT1) f: (null)   c: lpr -P cups-pdf  t: 20  port: 0
CONF: not allowing speaker port access
CONF: Packet Driver enabled.
CONF: config variable c_system unset
debug flags: B
Linux kernel 4.15.0; CPU speed is 1700000000 Hz
CPU-EMU speed is 1700 MHz
CONF: not running on console
CONF: mostly running as USER: uid=1000 (cached 1000) gid=1000 (cached 1000)
CONF: priv operations unavailable
DBG_FD already set
DOSEMU-2.0pre8 is coming up on Linux version 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64
Compiled with gcc version 7.3.0 64bit
CFLAGS: -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.hh -Wno-unused-result -Wcast-qual -Wwrite-strings -fplan9-extensions -Wno-maybe-uninitialized -fpie -ggdb3 -g -O2 -fdebug-prefix-map=/build/dosemu2-TdXHsk/dosemu2-2.0~pre8=. -fstack-protector-strong -Wformat -Werror=format-security
CONF: reserving 640Kb at 0x00000 for 'd' (Base DOS memory (first 640K))
CONF: reserving 8Kb at 0xFC000 for 'r' (Dosemu reserved area)
CONF: reserving 8Kb at 0xFE000 for 'b' (BIOS)
KVM: error opening /dev/kvm: Permiso denegado
KVM not available: Permiso denegado
using CPU emulation for vm86()
initial register values: fs: 0x0000  gs: 0x0000 eflags: 0x0246
initial segment bases: fs: 0x7f124400a740  gs: (nil)
VID: initializing SDL plugin
CONF: reserving 128Kb at 0xA0000 for 'v' (Video memory)
Conventional memory mapped from 0x7f122aef0000 to 0x40612000
DPMI memory mapped to 0x40722000 (reserve) and to 0x42722000 (main)
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))
VID: initializing video sdl
VID: SDL plugin initialization completed
Registering HWRAM, type=e base=0x4a918000 size=0x400000
CONF: reserving 4096Kb at 0x4A918000 for 'e' (VGAEMU LFB)
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)
SERIAL $Id$
Your fluidsynth is too old
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No existe el archivo o el directorio open /dev/snd/midiC0D0 failed
DPMI: mem init, mpool is 136273920 bytes at 0x42722000
CONF: detected layout is "es-latin1"
CONF: detected alternate layout: us
TIME: using 9154 usec for updating ALRM timer
======================= ENTER CPU-EMU ===============

CONF: freeing region for 'E' (EMS page frame)
ERROR: Bootable drive not found, exiting
leavedos(boot:145|0) called - shutting down
leavedos thread started
leavedos thread ended
coopthreads stopped
======================= LEAVE CPU-EMU ===============

**Comment by stsp** [comment]
This is a "known problem" with an explanation "dosemu2 is not written yet".
Some manual setup is needed.
Can you build the command.com from here?
https://github.com/stsp/comcom32
If not, I am attaching the binary here.
[comcom32.exe.gz](https://github.com/stsp/dosemu2/files/2894967/comcom32.exe.gz)

Now do `dosemu -install` and when it exits again,
put this comcom32.exe into ~/.dosemu/drive_c
Then symlink it to command.com.

**Comment by stsp** [comment]
Or alternatively, put comcom32 into `/usr/local/share/comcom32`
and symlink it to command.com there. dosemu2 will then find
it automatically.

**Comment by stsp** [comment]
Oh, no, its something else.
It would otherwise say
`ERROR: Neither FreeDOS nor comcom32 installation found.`
which is not what it says for you.
Where have you got the packages from?

**Comment by ZoccoCss** [comment]
I used ppa:dosemu2/ppa

**Comment by stsp** [comment]
OK, I removed everything and downloaded:
```
fdpp_0.1~beta4-0~201902210052~ubuntu19.04.1_amd64.deb
dosemu2_2.0~pre8-5451+19fac45~ubuntu19.04.1_amd64.deb
```

Installed, then:
```
$ dosemu
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: comcom32 not found, not doing install
ERROR: No drives defined, exiting
```

So for me the error msg is adequate.
Have you installed the same packages?

**Comment by stsp** [comment]
Please attach the `-D9+dD` log.
(attach means gzip and attach as a file, not copy/paste)

**Comment by ZoccoCss** [comment]
File attached
[boot2.log.gz](https://github.com/stsp/dosemu2/files/2895185/boot2.log.gz)

**Comment by stsp** [comment]
This is not a `-D9+dD` log.
You need to run `dosemu -D9+dD`

**Comment by ZoccoCss** [comment]
Apologies
[boot3.log.gz](https://github.com/stsp/dosemu2/files/2895244/boot3.log.gz)

**Comment by stsp** [comment]
Well, the log has now
```
ERROR: comcom32 not found, not doing install
ERROR: No drives defined, exiting
```

And so did the previous one, but not the one you
copy/pasted initially.
So I suppose you had different package installed initially?

**Comment by ZoccoCss** [comment]
Yes the comcom32 error was not there initially. I reinstalled it from the same ppa prior to sending the last log.

**Comment by stsp** [comment]
But there is no comcom32 in ppa, there is only fdpp.
You therefore couldn't install it from ppa.
So its still unclear why the msg changed.
Plus I don't see another part of msg, namely
```
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
```
which is strange. It should appear since you likely have
no freedos installed. Would it be possible to give me an ssh
to this machine? If not, can you build dosemu2 from sources?

**Comment by ZoccoCss** [comment]
We can stablish an ssh

**Comment by stsp** [comment]
Please mail me the data and I'll take a look
a few hours later.

**Comment by stsp** [comment]
Please confirm that everything works as expected now.

**Comment by ZoccoCss** [comment]
I downloaded the new version from the repository and now I get the message ERROR: fdpp not found, not doing intall. ERROR: No drives defined, exiting.

**Comment by stsp** [comment]
From what repository?
You had to upgrade the packages
from ubuntu ppa.

**Comment by stsp** [comment]
Use `make uninstall` to get rid of
what you got from repository. Then
upgrade packages.

**Comment by ZoccoCss** [comment]
I meant from the ppa. I used the following comands. 
sudo apt-get purge --auto-remove dosemu2
rm -rf ~/.dosemu
sudo apt-get install dosemu2

**Comment by stsp** [comment]
Could you please try that procedure
again? I didnt rebuild fdpp on LP, and
I guess dosemu2 build omitted fdpp
because the version was bumped to
beta-5. I hope automatic nightly builds
already fixed that.

**Comment by stsp** [comment]
No, there were no rebuilds.
I'll take care of that.

**Comment by ZoccoCss** [comment]
I am attaching the log file.
[boot4.log.gz](https://github.com/stsp/dosemu2/files/2900335/boot4.log.gz)

**Comment by stsp** [comment]
No need, I'll let you know when I manage to
create the proper build at LP. Currently it doesn't
let me to rebuild the same source.

**Comment by stsp** [comment]
Should now work.

**Comment by ZoccoCss** [comment]
Still getting an error. 
[boot5.log.gz](https://github.com/stsp/dosemu2/files/2900500/boot5.log.gz)

**Comment by stsp** [comment]
Have you done `rm -rf ~/.dosemu` after the last update?

**Comment by ZoccoCss** [comment]
Yes

**Comment by stsp** [comment]
Please open SSH.

**Comment by ZoccoCss** [comment]
SSH ready

**Comment by stsp** [comment]
I run it on your machine, and it boots
perfectly. I didn't do anything.
Wtf?

**Comment by ZoccoCss** [comment]
Yes. It now boots.

**Comment by stsp** [comment]
I didn't do anything!
You can look up the .bash_history to
make sure I only typed `dosemu` and `dosemu -t`

**Comment by ZoccoCss** [comment]
I don't know what happened either. Thank you so much.

**Comment by stsp** [comment]
Try `rm -rf ~/.dosemu` again, and if you find
that it doesn't start for the first time but subsequently
works, fill in another bug.

**Comment by stsp** [comment]
Indeed there was a bug that prevented the first boot.
It is now fixed.

**Comment by ZoccoCss** [comment]
Waiting for the ppa to be updated to test it.

**Comment by stsp** [comment]
I updated the PPA.

**Comment by ZoccoCss** [comment]
It boots.

**Comment by stsp** [comment]
Yes, and its a first time in dosemu2 history that
PPA packages boot.

**Comment by ZoccoCss** [comment]
Excelent!

**Comment by ZoccoCss** [comment]
Now I'm installing dosemu on a Debian machine and I get "ERROR: No drives defined, exiting"

I'm attaching the log file. 

[boot.log.gz](https://github.com/stsp/dosemu2/files/3052128/boot.log.gz)

**Comment by stsp** [comment]
ssh please.

**Comment by ZoccoCss** [comment]
I can't open this particular computer to the Internet. Could you please tell me, what additional information would you need or what steps do I need to take.

**Comment by stsp** [comment]
Attach a `-D9+cdD` log.
Also why can't you reproduce this on another computer?

**Comment by ZoccoCss** [comment]
The other computers have Ubuntu installed and use the ppa. This is the only Debian computer. 

I just git pulled and compiled the latest version and it's working. 

Thank you very much.

**Comment by stsp** [comment]
I still don't know what was the problem.
Would be good if you reset to da9f66f5aa6 and provide the log.

**Comment by ZoccoCss** [comment]
I don't know how to reset to  da9f66f so I did `git reset --hard da9f66f5aa61265a50d2bf183be4dc94675a1053` and reproduced the error. I'm attaching the log. 

[boot.log.gz](https://github.com/stsp/dosemu2/files/3056831/boot.log.gz)

**Comment by stsp** [comment]
> I don't know how to reset to da9f66f

Very simple: `git reset --h da9f66f`
Just a short for of what you already did.

> I'm attaching the log.

As usual, the needed logging is just not there.
I created the branch `tmp` where I added the
logging on top of the needed (old) revision.
Please re-do the log from `tmp` branch.

**Comment by ZoccoCss** [comment]
[boot.log.gz](https://github.com/stsp/dosemu2/files/3058951/boot.log.gz)

**Comment by stsp** [comment]
`default_drives 0` and why is so?
So you disable options, then ask why things stop working?

**Comment by ZoccoCss** [comment]
I have no idea how it got disabled.  

Now I compile the latest version and start to get the same error. How do I re-enable it?

[boot.log.gz](https://github.com/stsp/dosemu2/files/3059353/boot.log.gz)

**Comment by ZoccoCss** [comment]
I didn't make any modifications to the dosemu.conf file in the debian computer. Don't understand why this error happens in `da9f66f` but not in the current one. 

In regards to the debian file, I'm attaching an image of the error. 

![Screenshot from 2019-04-09 16-16-37](https://user-images.githubusercontent.com/47893772/55832500-b4dd7880-5ae3-11e9-9f40-9dfa6db1a4cd.png)

I also tried the -d flag and it didn't work.

**Comment by stsp** [comment]
> I didn't make any modifications to the dosemu.conf file in the debian computer.

Maybe there is an older dosemu.conf from previous
install? Check for `$_default_drives` in `/etc/dosemu/dosemu.conf`.

> I also tried the -d flag and it didn't work.

It says, unmet dependencies, fdpp.
You need to install fdpp, and from the package, not
by "make install".

**Comment by stsp** [comment]
> but not in the current one.

Because currently this option is no longer in use.
But if you have an altered options somewhere, you'd
better find the source of the problem.
Try removing dosemu.conf, maybe that will help.

**Comment by ZoccoCss** [comment]
You are right. After I made the fdpp deb package, I had no trouble making the deb for dosemu2. 

Thank you again for the excellent software.
