### ISSUE TITLE
ViewDocs doesn't work

### ISSUE THREAD

**Issue by JL2210** [stsp/dosemu2#805]
Every single option gives a "No such file or directory" error:

```
chronos@localhost ~/Downloads/git/dosemu2 $ ./ViewDocs 

The files ./doc/*.txt are BOLDFACE formatted. Apparently this confuses some of
our users, so we just supply this script to help them ;-)

What info do you want to be displayed ? (enter a number)
(press the q key to exit the viewer)

1) dosemu.conf chapter  4) dosemu manpage       7) dosemu-HOWTO.txt
2) README.txt           5) dosemu.bin manpage
3) README-tech.txt      6) configuration.txt
#? 1
./ViewDocs: line 17: doc/README.txt: No such file or directory
+: No such file or directory
./doc/README.txt: No such file or directory
chronos@localhost ~/Downloads/git/dosemu2 $ ./ViewDocs 

The files ./doc/*.txt are BOLDFACE formatted. Apparently this confuses some of
our users, so we just supply this script to help them ;-)

What info do you want to be displayed ? (enter a number)
(press the q key to exit the viewer)

1) dosemu.conf chapter  4) dosemu manpage       7) dosemu-HOWTO.txt
2) README.txt           5) dosemu.bin manpage
3) README-tech.txt      6) configuration.txt
#? 2
./doc/README.txt: No such file or directory
./doc/README.txt: No such file or directory
chronos@localhost ~/Downloads/git/dosemu2 $ ./ViewDocs 

The files ./doc/*.txt are BOLDFACE formatted. Apparently this confuses some of
our users, so we just supply this script to help them ;-)

What info do you want to be displayed ? (enter a number)
(press the q key to exit the viewer)

1) dosemu.conf chapter  4) dosemu manpage       7) dosemu-HOWTO.txt
2) README.txt           5) dosemu.bin manpage
3) README-tech.txt      6) configuration.txt
#? 3
./doc/README-tech.txt: No such file or directory
chronos@localhost ~/Downloads/git/dosemu2 $ ./ViewDocs 

The files ./doc/*.txt are BOLDFACE formatted. Apparently this confuses some of
our users, so we just supply this script to help them ;-)

What info do you want to be displayed ? (enter a number)
(press the q key to exit the viewer)

1) dosemu.conf chapter  4) dosemu manpage       7) dosemu-HOWTO.txt
2) README.txt           5) dosemu.bin manpage
3) README-tech.txt      6) configuration.txt
#? 6
./doc/configuration.txt: No such file or directory
chronos@localhost ~/Downloads/git/dosemu2 $ ./ViewDocs 

The files ./doc/*.txt are BOLDFACE formatted. Apparently this confuses some of
our users, so we just supply this script to help them ;-)

What info do you want to be displayed ? (enter a number)
(press the q key to exit the viewer)

1) dosemu.conf chapter  4) dosemu manpage       7) dosemu-HOWTO.txt
2) README.txt           5) dosemu.bin manpage
3) README-tech.txt      6) configuration.txt
#? 7
./doc/dosemu-HOWTO.txt: No such file or directory
```

**Comment by stsp** [comment]
Should now be fixed.

**Comment by JL2210** [comment]
It still doesn't work. Now it's just not there. Instead of removing things, can you actually fix them?

**Comment by stsp** [comment]
Why can't you view them?
They are here:
https://rawgit.com/stsp/dosemu2/devel/doc/README.html
