### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by andrewbird** [stsp/dosemu2#870]
**Describe the bug**
Build breaks for me on 32 bit, also Launchpad builds are failing on both 64 and 32 bit. The fix is non obvious to me.

**To Reproduce**
./default_configure -d
make
~~~
make[2]: Entering directory '/clients/common/dosemu2.git/src/arch/linux/async'
gcc -c -MMD -DCFLAGS_STR="-Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.hh -Wno-unused-result -Wcast-qual -Wwrite-strings -fplan9-extensions -Wno-maybe-uninitialized -fno-pie -fsanitize=undefined -fno-sanitize=alignment -ggdb3 -O0   " -I../../../../src/include -I../../../../src/plugin/include -I../../../../src/base/bios/x86 -I/clients/common/dosemu2.git/src/include -I/clients/common/dosemu2.git/src/base/lib  -I/clients/common/dosemu2.git/src/base/lib/mcontext -Wall -Wstrict-prototypes -Wmissing-declarations -Wnested-externs -fms-extensions -pthread -imacros config.hh -Wno-unused-result -Wcast-qual -Wwrite-strings -fplan9-extensions -Wno-maybe-uninitialized -fno-pie -fsanitize=undefined -fno-sanitize=alignment -ggdb3 -O0    -o signal.o signal.c
signal.c:56:10: warning: #warning Not disabling SIGALTSTACK_WA, update your kernel [-Wcpp]
         #warning Not disabling SIGALTSTACK_WA, update your kernel
          ^~~~~~~
signal.c:475:1: error: expected identifier or ‘(’ before ‘}’ token
 }
 ^
~~~

**Comment by stsp** [comment]
Should now be fixed.
Something bad with glibc...

**Comment by andrewbird** [comment]
Still getting error above on 32bit, perhaps there were two problems?

**Comment by stsp** [comment]
Indeed, thanks!
Should now be fixed.

**Comment by andrewbird** [comment]
Thanks, it's now building again.
