### ISSUE TITLE
dosemu2 fail to start with ERROR: shared memory map failed, exiting

### ISSUE THREAD

**Issue by domichel** [stsp/dosemu2#936]
When starting dosemu, I get

INFO: booting with comcom32, this is very experimental
INFO: fdpp booting, this is very experimental!
mmap(): Opération non permise
ERROR: shared memory map failed, exiting

**To Reproduce**
Install dosemu2 and run it with, or without any ~/.dosemu and ~/.dosemurc

[boot.log](https://github.com/stsp/dosemu2/files/3718676/boot.log)

**Comment by domichel** [comment]
```
# mount 
devtmpfs on /dev type devtmpfs (rw,nosuid,relatime,size=10240k,nr_inodes=469861,mode=755) 
... 
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime) 


# df -h 
Filesystem      Size  Used Avail Use% Mounted on 
... 
devtmpfs         10M     0   10M   0% /dev 
tmpfs           368M  1.1M  367M   1% /run 
shm             1.8G  221M  1.6G  12% /dev/shm 


# ls -1l /dev|grep shm 
drwxrwxrwt 3 root root           320 Oct 11 13:37 shm 


# ls -1l /dev/shm 
total 80444 
-rw------- 1 dom fvwm-crystal    65536 Oct 10 12:21 dosemu_dpmishm_11921_ldt_alias 
-rw------- 1 dom fvwm-crystal    65536 Oct 11 13:11 dosemu_dpmishm_30378_ldt_alias 
-rw------- 1 dom fvwm-crystal    65536 Oct 11 13:20 dosemu_dpmishm_32125_ldt_alias 
-rw------- 1 dom fvwm-crystal    65536 Oct 11 12:36 dosemu_dpmishm_8249_ldt_alias 
-rw------- 1 dom fvwm-crystal    65536 Oct 11 12:37 dosemu_dpmishm_8533_ldt_alias 
-rw-r--r-- 1 dom fvwm-crystal 82280346 Oct 11 13:21 jack-1001-0 
-rw-r--r-- 1 dom fvwm-crystal     1187 Oct 11 13:21 jack-1001-1 
-rw-rw-rw- 1 dom fvwm-crystal    70744 Oct 10 12:08 jack-shm-registry 
drwxr-x--- 2 dom fvwm-crystal      120 Oct 11 13:20 jack_db 
srwxr-xr-x 1 dom fvwm-crystal        0 Oct 11 13:21 jack_default_1001_0 
-rwxr-xr-x 1 dom fvwm-crystal       12 Oct 10 12:08 jack_sem.1001_default_a2j 
-rwxr-xr-x 1 dom fvwm-crystal       12 Oct 11 13:21 jack_sem.1001_default_dbusapi 
-rwxr-xr-x 1 dom fvwm-crystal 12 Oct 11 13:21 jack_sem.1001_default_freewheel 
-rwxr-xr-x 1 dom fvwm-crystal 12 Oct 11 13:21 jack_sem.1001_default_system 
```
```
 # sysctl -a|grep mmap
vm.mmap_min_addr = 0
vm.mmap_rnd_bits = 28
vm.mmap_rnd_compat_bits = 8
```
I try vm.mmap_min_addr = 4096 (it's gentoo default setting), but with the same result.

```
 # sysctl -a|grep mem
net.core.optmem_max = 20480
net.core.rmem_default = 212992
net.core.rmem_max = 4194304
net.core.wmem_default = 212992
net.core.wmem_max = 1048576
net.ipv4.fib_sync_mem = 524288
net.ipv4.igmp_max_memberships = 20
net.ipv4.tcp_mem = 43869	58494	87738
net.ipv4.tcp_rmem = 4096	131072	6291456
net.ipv4.tcp_wmem = 4096	16384	4194304
net.ipv4.udp_mem = 87741	116988	175482
net.ipv4.udp_rmem_min = 4096
net.ipv4.udp_wmem_min = 4096
vm.lowmem_reserve_ratio = 256	256	32	0
vm.memory_failure_early_kill = 0
vm.memory_failure_recovery = 1
vm.nr_hugepages_mempolicy = 0
vm.overcommit_memory = 0
```

**Comment by stsp** [comment]
You need to remove noexec flag on /dev/shm.
I added the error messages to suggest this.

@kees @amluto could you please provide us with
the current status on PROT_EXEC mappings on the
mnt_noexec filesystems? The previous agreement
was that mmap(PROT_EXEC) will fail but if you
do mmap() w/o PROT_EXEC and then do
mprotect(PROT_EXEC) then things should work.
And they worked.
But now I find this work-around broken and mprotect()
returns -EPERM.
So is there no way of doing the exec-capable
mappings of posix shm? Any suggestions?
I've googled this patch:
https://lwn.net/Articles/455256/
But it doesn't seem to be applied? Why?

**Comment by domichel** [comment]
> You need to remove noexec flag on /dev/shm.
> I added the error messages to suggest this.


Thank you. It was it and my system survived the change. I will add a message about that for the user into the ebuild.

**Comment by stsp** [comment]
I am working on a work-around...

**Comment by stsp** [comment]
Should now work.
But once again kernel change breaks our setups...

**Comment by domichel** [comment]
> Should now work.
> But once again kernel change breaks our setups...
It is not a kernel change, it is it's config that I changed. But it is up to the user to configure /dev/shm into fstab if wanted. It is not done by the ebuild. My previous setting with noexec was the default setting of my kernel (gentoo does not provide precompiled kernels, but an ebuild can check for mandatory kernel options, which dosemu2 ebuild doesn't do at that time), and to return to this, all I have to do is to remove the line I added before in /etc/fstab and reboot.

In the meantime, I can confirm than dosemu works fine here with exec on /dev/shm and your last patch.

**Comment by stsp** [comment]
Please confirm noexec.
With exec it worked before.

**Comment by stsp** [comment]
Its a kernel change: we had already
the noexec work-around, but it got
broken. I implemented a new one.
I will try to contact the author of the
aforementioned patch who tried to
fix that problem.

**Comment by stsp** [comment]
Ideally there should be no silly
work-arounds at all, not to speak
about breaking them every now
and then. I find this unsatisfactory.

**Comment by domichel** [comment]
> > In the meantime, I can confirm than dosemu works fine here with exec
> 
> Please confirm noexec.
> With exec it worked before.

I confirm it:
```
#: mount
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime)
```
```
#: dosemu
ERROR: MAPPING: cannot mmap shared memory pool, Permission non accordée
INFO: booting with comcom32, this is very experimental
INFO: fdpp booting, this is very experimental!
```
dosemu boot fine and nice.

**Comment by domichel** [comment]
> Ideally there should be no silly
> work-arounds at all, not to speak
> about breaking them every now
> and then. I find this unsatisfactory.

The jack-audio-connection-kit exercise /dev/shm a lot and is happy with both "exec" and "noexec". Maybe you can contact the author to get a fast pointer on how they implemented it.

**Comment by stsp** [comment]
jack uses it for audio and dosemu -
for code. Obviously for audio noexec
does not matter. There are lots of ways
of implementing posix shm properly and
securely, but kernel guys choose to
break things, so I need to contact them,
not the jack author.

**Comment by domichel** [comment]
Oh OK.

As I am talking about jack, I can confirm something else. dosemu2 works fine when jackd is up and running with the alsa to jack ALSA plugin configured as default ALSA sound card. dosemu2 appear into the jack graph as a stereo audio alsa->jack plugin which is auto-connected to the main stereo output of jack. It is also a VirtualRawMidi output that can be used with any jack Midi input port. 

No configuration is needed for dosemu for that. It must be compiled with alsa support (and midi support for the raw midi output), and as with any other ALSA software, it just work when JACK is configured to use the alsa to jack ALSA plugin (on gentoo, media-sound/alsa-plugins with USE=jack). In clear, that mean than dosemu2 can be used into a professional audio setup. This setup is part of any linux audio pro setup, which imply it must just work for such users.

For a pulseaudio desktop audio setup, the same can be done with USE=pulseaudio for the alsa-plugins (plugin pulseaudio of the alsa-plugins). Anyway, the documentation of you favorite distribution must explain you how to interface alsa with pulseaudio in order to get dosemu into pulseaudio. I will not test it because to install pulseaudio would force me to install software I don't want into my current system, but it should just work if pulseaudio is configured to use the alsa sinks.

**Comment by stsp** [comment]
dosemu2 uses SDL or libao for audio
output, both of which have the jack support.
dosemu2 does not support alsa output
directly. As such, I find it quite bad that
you have the alsa->jack route for dosemu2,
because this means the native jack output
of sdl2 (or libao) is not active for you. Maybe
you need to rebuild sdl2 with jack support.

Same is for midi. dosemu2 normally uses
fluidsynth for GM and munt for mt32. if it
went the VirtualRawMidi route then some
components are missing.

> For a pulseaudio desktop audio setup, the same can be done with
> USE=pulseaudio for the alsa-plugins

No, SDL supports pulseaudio natively, so there
is no place for alsa plugins in that scheme. You
make it the emulation-over-emulation-over-emulation,
but there are shorter routes exist.

> Anyway, the documentation of you favorite distribution must explain
> you how to interface alsa with pulseaudio in order to get dosemu into pulseaudio.

No, everything should work out of the box,
if properly built. When you need to write a
lot of docs, something is wrong. And alsa
is definitely out of the picture, I didn't even
write an audio output support for it.

**Comment by stsp** [comment]
Following the @redpig suggestion I replaced
the use of shm_open() with memfd_create()
for the cases where anonymous shm is enough.
shm_open() is still used for the named shm
case (not sure about the replacement), but
in this case, fortunately, I was able to get rid
of PROT_EXEC with a few hacks.
So more or less this problem is solved.

**Comment by stsp** [comment]
> For a pulseaudio desktop audio setup, the same can be done with USE=pulseaudio
> for the alsa-plugins

For example, for me pulseaudio sees dosemu2 as:
"dosemu.bin: Simple DirectMedia Layer".
If it sees your dosemu as alsa redirect, then things
are going wrong.

**Comment by domichel** [comment]
The gentoo ebuild for libsdl2 have no USE flag for jack, which imply it add the jack support if it find it. Into my system I get:

```
SDL2 Configure Summary:
Building Shared Libraries
Enabled modules : atomic audio video render events joystick haptic sensor power filesystem threads timers file loadso cpuinfo assembly
Assembly Math   : mmx sse sse2 sse3
Audio drivers   : disk dummy alsa jack(dynamic)
Video drivers   : dummy x11 opengl
X11 libraries   : xcursor xdbe xinerama xinput2 xinput2_multitouch xrandr xshape xvidmode
Input drivers   : linuxev linuxkd
Using libsamplerate : YES
Using libudev       : YES
Using dbus          : YES
Using ime           : YES
Using ibus          : NO
Using fcitx         : NO
>>> Source configured.
```

For alsa, the libsdl2 ebuild enable alsa, but disable dynamic alsa. Maybe I should try the same for jack, and if it work, fill a gentoo bug. Or maybe sdl2 will use alsa per default when both alsa and jack are present, and that even when jack is running.

For libao, it is libao-1.2.2 on gentoo, and if I run "./configure --help" in its source, it have no jack support.

**Comment by domichel** [comment]
Well, I find a simplest way:

`SDL_AUDIODRIVER="jack" dosemu`

dosemu appear as "SDL" into jack.

**Comment by domichel** [comment]
> Same is for midi. dosemu2 normally uses
> fluidsynth for GM and munt for mt32. if it
> went the VirtualRawMidi route then some
> components are missing.

munt don't exist on gentoo, and my fluidsynth version is too old. I can update fluidsynth to  the latest version, but it would break tuxguitar. I just see than tuxguitar was removed from gentoo, and it is a new tuxguitar version on sourceforge. I will try to fix all this with my next system update.

**Comment by stsp** [comment]
> Or maybe sdl2 will use alsa per default when both alsa and jack are present

Sounds plausible, perhaps sdl devs do not
recognize jack as popular enough. But at
least pulseaudio takes the priority over alsa.

> For libao, it is libao-1.2.2 on gentoo, and if I run "./configure --help" in its source,
> it have no jack support.

There is some, but probably unofficial:
https://aur.archlinux.org/packages/libao-jack/

> my fluidsynth version is too old.

This only means that it couldn't find sound font.
For old fluidsynth the hardcoded search pathes
are used:
```
        "/usr/share/soundfonts/default.sf2",            // fedora
        "/usr/share/soundfonts/FluidR3_GM.sf2",         // fedora
        "/usr/share/sounds/sf2/FluidR3_GM.sf2.flac",    // ubuntu
        "/usr/share/sounds/sf2/FluidR3_GM.sf2",         // debian
```
I can add to that list.

**Comment by domichel** [comment]
On gentoo, the "old" fluidsynth version is 1.1.11 and it  provide no soundfont. The synth.default-soundfont is /usr/share/soundfonts/default.sf2, but it doesn't exist.  

2 soundfonts are provided by media-sound/fluid-soundfont-3.1. They are installed in  /usr/share/sounds/sf2/FluidR3_GM.sf2 and /usr/share/sounds/sf2/FluidR3_GS.sf2, but fluidsynth doesn't find it because its default soundfont point to that non existing sf file.

If I make a symlink /usr/share/soundfonts/default.sf2 -> /usr/share/sounds/sf2/FluidR3_GM.sf2, dosemu still use the virtual midi route:

```
Initializing SDL sound output
fluidsynth: loaded soundfont /usr/share/soundfonts/default.sf2 ID=1
MIDI Input: named pipe: unable to open /home/dom/.dosemu/run/dosemu-midi_in for reading: Aucun fichier ou dossier de ce type
SB: SB Initialisation
SB: Mixer init
SB: OPL3 Initialization
MPU401: MPU-401 Initialisation
SB: mpu401 irq set to 5
SB: same irq for DSP and MPU401
MPU401: MPU-401 Initialisation - Base 0x330 
SB: Initialisation - Base 0x220
cpu_vm_dpmi set to 3
DPMI: mem init, mpool is 136273920 bytes at 0x43e59000
CONF: detected layout is "sg"
CONF: detected alternate layout: (null)
TIME: using 9154 usec for updating ALRM timer
SB: Resetting SB DSP
CONF: freeing region for 'E' (EMS page frame)
INFO: booting with comcom32, this is very experimental
INFO: fdpp booting, this is very experimental!

```

**Comment by stsp** [comment]
It probably enables both drivers.
I dont remember the default heuristic.
You can limit it with
§_midi_driver="fluid"
And you dont need the symlink.

**Comment by stsp** [comment]
No. looking at the heuristic code I think it
won't open alsa together with fluidsynth.
Please add the -D9+S log.

**Comment by stsp** [comment]
Btw, I've just fixed a horrible bug that the
header file was missing in ladspa plugin
(forgotten "git add"). So ladspa support
was never enabled.

**Comment by domichel** [comment]
I now get a line about ladspa into the logs. Here are 2 of them.

Default config (without ~/.dosemurc):
[boot.defaultconf.log](https://github.com/stsp/dosemu2/files/3736317/boot.defaultconf.log)

With $_midid_driver="fluid" and fluidsynth-2.0.4:
[boot.midifluid.log](https://github.com/stsp/dosemu2/files/3736334/boot.midifluid.log)

**Comment by stsp** [comment]
Should now work.
In your case timidity was used, not alsa.

**Comment by domichel** [comment]
It is better, but fluidsynth still fail to start with:
```
fluidsynth: cannot get samplerate
PCM: Initializing plugin: MIDI Output: Fluidsynth devive (w=3): Failed
```
I use jackdbus from the last devel code of jack-audio-connection-kit. It is started by cadence at 48kHz. I get the same result if I change the jack setting to use 44.1kHz.

It is another error related to MIDI::
`MIDI Input: named pipe: unable to open /home/dom/.dosemu/run/dosemu-midi_in for reading: No file or directory of that type`

[boot.log](https://github.com/stsp/dosemu2/files/3743507/boot.log)

**Comment by stsp** [comment]
> It is better, but fluidsynth still fail to start with:

Not a problem because later timidity starts fine.

> It is another error related to MIDI::

Not a problem, dosemu2 tries many things and
find those that work. Not everything should work
at once.

**Comment by stsp** [comment]
> Not a problem because later timidity starts fine.

That was a rather dumb statement of me,
I have to admit.
I forgot to tell you instead that it was fixed
in 52ac3af8
